In [1]:
import numpy as np
import pandas as pd
from pathlib import Path

from sklearn.metrics import roc_auc_score

PROJECT_ROOT = Path("/mnt/c/dev/my_ml_project")

DATA_DIR = PROJECT_ROOT / "data"
OOF_DIR = PROJECT_ROOT / "oof_preds"
SUB_DIR = PROJECT_ROOT / "submissions"

TRAIN_PATH = DATA_DIR / "train.csv"
TARGET = "임신 성공 여부"

SAVE_DIR = PROJECT_ROOT / "analysis" / "oof_slice"
SAVE_DIR.mkdir(parents=True, exist_ok=True)

print("PROJECT_ROOT:", PROJECT_ROOT)
print("TRAIN_PATH exists:", TRAIN_PATH.exists())
print("SAVE_DIR:", SAVE_DIR)

PROJECT_ROOT: /mnt/c/dev/my_ml_project
TRAIN_PATH exists: True
SAVE_DIR: /mnt/c/dev/my_ml_project/analysis/oof_slice

In [2]:
def data_preprocessing(df):
    df = df.copy()
    time_cols = [
        '임신 시도 또는 마지막 임신 경과 연수',
        '난자 해동 경과일',
        '난자 혼합 경과일',
        '배아 이식 경과일',
        '배아 해동 경과일'
    ]

    for col in time_cols:
        df[f'{col}_performed'] = (
            df[col].notnull()
        ).astype(int)


    df = df.fillna(0)
    infertility_cols = [
        '불임 원인 - 난관 질환',
        '불임 원인 - 남성 요인',
        '불임 원인 - 배란 장애',
        '불임 원인 - 여성 요인',
        '불임 원인 - 자궁경부 문제',
        '불임 원인 - 자궁내막증',
        '불임 원인 - 정자 농도',
        '불임 원인 - 정자 운동성',
        '불임 원인 - 정자 형태',
        '불임 원인 - 정자 면역학적 요인'
    ]

    male_cols = [
        '불임 원인 - 남성 요인',
        '불임 원인 - 정자 농도',
        '불임 원인 - 정자 운동성',
        '불임 원인 - 정자 형태',
        '불임 원인 - 정자 면역학적 요인'
    ]

    female_cols = [
        '불임 원인 - 난관 질환',
        '불임 원인 - 배란 장애',
        '불임 원인 - 여성 요인',
        '불임 원인 - 자궁경부 문제',
        '불임 원인 - 자궁내막증'
    ]

    df['불임원인_총개수'] = df[infertility_cols].sum(axis=1)

    df['남성_원인_수'] = df[male_cols].sum(axis=1)

    df['여성_원인_수'] = df[female_cols].sum(axis=1)

    df['남녀_복합_원인'] = (
        (df['남성_원인_수'] > 0) &
        (df['여성_원인_수'] > 0)
    ).astype(int)

    df['원인불명'] = (
        df['불임원인_총개수'] == 0
    ).astype(int)

    count_cols = [
        '총 시술 횟수',
        'IVF 시술 횟수',
        'DI 시술 횟수',
        '총 임신 횟수',
        'IVF 임신 횟수',
        'DI 임신 횟수',
        '총 출산 횟수',
        'IVF 출산 횟수',
        'DI 출산 횟수',
        '클리닉 내 총 시술 횟수'
    ]

    count_map = {
        '0회': 0,
        '1회': 1,
        '2회': 2,
        '3회': 3,
        '4회': 4,
        '5회': 5,
        '6회 이상': 6,
    }

    for col in count_cols:
        df[col] = df[col].map(count_map).astype(float)

    df['고령여부'] = df['시술 당시 나이'].isin([
        '만38-39세',
        '만40-42세',
        '만43-44세',
        '만45-50세'
    ]).astype(int)


    df['배아_생성률'] = np.where(
        df['혼합된 난자 수'] == 0,
        0,
        df['총 생성 배아 수'] / df['혼합된 난자 수']
    )

    # 2. 배아 이식 효율
    df['배아_이식률'] = np.where(
        df['총 생성 배아 수'] == 0,
        0,
        df['이식된 배아 수'] / df['총 생성 배아 수']
    )

    # 3. 배아 냉동 비율
    df['배아_냉동률'] = np.where(
        df['총 생성 배아 수'] == 0,
        0,
        df['저장된 배아 수'] / df['총 생성 배아 수']
    )
    df['IVF_임신성공률'] = np.where(
        df['IVF 시술 횟수'] == 0,
        0,
        df['IVF 임신 횟수'] / df['IVF 시술 횟수']
    )

    df['DI_임신성공률'] = np.where(
        df['DI 시술 횟수'] == 0,
        0,
        df['DI 임신 횟수'] / df['DI 시술 횟수']
    )

    df['고령_난자수_interaction'] = (
        df['고령여부'] *
        df['수집된 신선 난자 수']
    )

    df['배아이식_수행여부'] = (
        df['이식된 배아 수'] > 0
    ).astype(int)

    df['배아_이식_집중도'] = np.where(
        (df['이식된 배아 수'] + df['저장된 배아 수']) == 0,
        0,
        df['이식된 배아 수'] /
        (
            df['이식된 배아 수'] +
            df['저장된 배아 수']
        )
    )
    df["배아 생성 주요 이유"] = (
        df["배아 생성 주요 이유"]
        .astype(str)
        .astype("category")
    )
    df["특정 시술 유형"] = (
        df["특정 시술 유형"]
        .astype(str)
        .astype("category")
    )

    # 고령 × 이식 배아 수
    df['고령_배아이식'] = (
        df['고령여부'] *
        df['이식된 배아 수']
    )

    # 고령 × 총 생성 배아 수
    df['고령_배아생성'] = (
        df['고령여부'] *
        df['총 생성 배아 수']
    )

    # 고령 × 저장 배아 수
    df['고령_배아저장'] = (
        df['고령여부'] *
        df['저장된 배아 수']
    )

    # 고령 × 미세주입 난자 수
    df['고령_미세주입난자'] = (
        df['고령여부'] *
        df['미세주입된 난자 수']
    )

    df['출산_임신_전환율'] = np.where(
        df['총 임신 횟수'] == 0,
        0,
        df['총 출산 횟수'] / df['총 임신 횟수']
    )

    df['클리닉_집중도'] = np.where(
        df['총 시술 횟수'] == 0,
        0,
        df['클리닉 내 총 시술 횟수'] / df['총 시술 횟수']
    )

    df['첫_시술_여부'] = (
        df['총 시술 횟수'] == 0
    ).astype(int)



    binary_keywords = [
        "코드", "나이", "유형", "여부", "원인", "이유", "횟수", "출처"
    ]

    binary_cols = [
        col for col in df.columns
        if any(keyword in col for keyword in binary_keywords)
    ]

    df[binary_cols] = df[binary_cols].astype('category')

    object_cols = df.select_dtypes(include="object").columns

    df[object_cols] = df[object_cols].astype(str)

    cat_cols = df.select_dtypes(
        include=["object", "category", "string"]
    ).columns.tolist()

    for col in cat_cols:
        if col != TARGET:
            df[col] = df[col].astype(str)

    drop_cols = [
        '배아이식_수행여부'
    ]
    df = df.drop(
        columns=drop_cols
        )
    return df

In [3]:
train_raw = pd.read_csv(TRAIN_PATH)

y = train_raw[TARGET].astype(int).reset_index(drop=True)
X_raw = train_raw.drop(columns=[TARGET]).reset_index(drop=True)

print("X_raw:", X_raw.shape)
print("y:", y.shape)
print("target mean:", y.mean())

X_raw: (256351, 68)
y: (256351,)
target mean: 0.2583489044318142

In [4]:
seed42_oof = np.load(OOF_DIR / "combo_te_s10" / "final_combo_rank.npy")
seed2024_oof = np.load(OOF_DIR / "combo_te_v1_s10_seed2024" / "final_oof_seed2024.npy")
seed777_oof = np.load(OOF_DIR / "combo_te_v1_s10_seed777" / "final_oof_seed777.npy")
seed999_oof = np.load(OOF_DIR / "combo_te_v1_s10_seed999" / "final_oof_seed999.npy")

champion_oof = (
    seed42_oof +
    seed2024_oof +
    seed777_oof +
    seed999_oof
) / 4

print("seed42:", roc_auc_score(y, seed42_oof))
print("seed2024:", roc_auc_score(y, seed2024_oof))
print("seed777:", roc_auc_score(y, seed777_oof))
print("seed999:", roc_auc_score(y, seed999_oof))
print("champion 4-seed:", roc_auc_score(y, champion_oof))

seed42: 0.7404963277840849
seed2024: 0.7405675120287843
seed777: 0.7404199005438702
seed999: 0.7404124217483375
champion 4-seed: 0.7407705074934163

In [5]:
analysis_df = X_raw.copy()
analysis_df["target"] = y
analysis_df["pred"] = champion_oof

analysis_df["abs_error"] = np.abs(analysis_df["target"] - analysis_df["pred"])
analysis_df["pred_rank"] = pd.Series(champion_oof).rank(pct=True).values

analysis_df.head()

,ID,시술 시기 코드,시술 당시 나이,임신 시도 또는 마지막 임신 경과 연수,시술 유형,특정 시술 유형,배란 자극 여부,배란 유도 유형,단일 배아 이식 여부,착상 전 유전 검사 사용 여부,...,PGS 시술 여부,난자 채취 경과일,난자 해동 경과일,난자 혼합 경과일,배아 이식 경과일,배아 해동 경과일,target,pred,abs_error,pred_rank
0,TRAIN_000000,TRZKPL,만18-34세,NaN,IVF,ICSI,1,기록되지 않은 시행,0.0,NaN,...,NaN,0.0,NaN,0.0,3.0,NaN,0,0.918868,0.918868,0.920788
1,TRAIN_000001,TRYBLT,만45-50세,NaN,IVF,ICSI,0,알 수 없음,0.0,NaN,...,NaN,0.0,NaN,0.0,NaN,NaN,0,0.025578,0.025578,0.017102
2,TRAIN_000002,TRVNRY,만18-34세,NaN,IVF,IVF,1,기록되지 않은 시행,0.0,NaN,...,NaN,0.0,NaN,0.0,2.0,NaN,0,0.673969,0.673969,0.674708
3,TRAIN_000003,TRJXFG,만35-37세,NaN,IVF,ICSI,1,기록되지 않은 시행,0.0,NaN,...,NaN,0.0,NaN,0.0,NaN,NaN,0,0.095958,0.095958,0.101556
4,TRAIN_000004,TRVNRY,만18-34세,NaN,IVF,ICSI,1,기록되지 않은 시행,0.0,NaN,...,NaN,0.0,NaN,0.0,3.0,NaN,0,0.621466,0.621466,0.621234

In [6]:
X_proc = data_preprocessing(X_raw).reset_index(drop=True)

# 보고 싶은 engineered feature만 analysis_df에 붙이기
engineered_slice_cols = [
    "배아_이식_집중도",
    "배아_생성률",
    "배아_이식률",
    "배아_냉동률",
    "IVF_임신성공률",
    "DI_임신성공률",
    "고령여부",
    "고령_난자수_interaction",
    "출산_임신_전환율",
    "클리닉_집중도",
    "배아 이식 경과일_performed",
    "배아 해동 경과일_performed",
    "난자 혼합 경과일_performed",
]

for col in engineered_slice_cols:
    if col in X_proc.columns:
        analysis_df[col] = X_proc[col].values

print("analysis_df:", analysis_df.shape)

/tmp/ipykernel_757/835862898.py:209: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  object_cols = df.select_dtypes(include="object").columns

analysis_df: (256351, 85)

In [7]:
def slice_auc_report(
    df,
    col,
    target_col="target",
    pred_col="pred",
    min_count=500,
    top_n=30,
):
    rows = []

    temp = df[[col, target_col, pred_col]].copy()
    temp[col] = temp[col].astype(str).fillna("NaN")

    for value, g in temp.groupby(col):
        n = len(g)
        pos = int(g[target_col].sum())
        neg = n - pos

        if n < min_count:
            continue

        # AUC는 target이 양/음 둘 다 있어야 계산 가능
        if g[target_col].nunique() < 2:
            auc = np.nan
        else:
            auc = roc_auc_score(g[target_col], g[pred_col])

        rows.append({
            "col": col,
            "value": value,
            "count": n,
            "positive": pos,
            "negative": neg,
            "positive_rate": g[target_col].mean(),
            "pred_mean": g[pred_col].mean(),
            "calibration_gap": g[pred_col].mean() - g[target_col].mean(),
            "auc": auc,
            "pred_std": g[pred_col].std(),
        })

    result = pd.DataFrame(rows)

    if result.empty:
        return result

    result = result.sort_values(
        ["auc", "count"],
        ascending=[True, False],
        na_position="last"
    )

    return result.head(top_n)

In [10]:
categorical_slice_cols = [
    "시술 시기 코드",
    "시술 유형",
    "특정 시술 유형",
    "배란 유도 유형",
    "배란 자극 여부",
    "시술 당시 나이",
    "난자 출처",
    "정자 출처",
    "난자 기증자 나이",
    "정자 기증자 나이",
    "배아 생성 주요 이유",
    "신선 배아 사용 여부",
    "동결 배아 사용 여부",
    "기증 배아 사용 여부",
    "대리모 여부",
]

categorical_slice_cols = [
    col for col in categorical_slice_cols
    if col in analysis_df.columns
]

all_cat_reports = []

for col in categorical_slice_cols:
    print("\n" + "=" * 80)
    print("Slice:", col)

    report = slice_auc_report(
        analysis_df,
        col=col,
        min_count=500,
        top_n=30,
    )

    display(report)

    if not report.empty:
        all_cat_reports.append(report)

cat_report_df = pd.concat(all_cat_reports, ignore_index=True)
cat_report_df.to_csv(SAVE_DIR / "categorical_slice_auc_report.csv", index=False)

display(
    cat_report_df.sort_values(
        ["auc", "count"],
        ascending=[True, False],
        na_position="last"
    ).head(50)
)

def numeric_bin_report(
    df,
    col,
    bins=5,
    target_col="target",
    pred_col="pred",
    min_count=500,
):
    temp = df[[col, target_col, pred_col]].copy()
    numeric = pd.to_numeric(temp[col], errors="coerce")

    bin_col = f"{col}_bin"

    # unique가 적으면 그대로 category 취급하되,
    # Int64로 강제 변환하지 않는다.
    if numeric.nunique(dropna=True) <= 10:
        temp[bin_col] = numeric.round(6).astype(str)
    else:
        try:
            temp[bin_col] = pd.qcut(
                numeric,
                q=bins,
                duplicates="drop"
            ).astype(str)
        except Exception:
            temp[bin_col] = pd.cut(
                numeric,
                bins=bins
            ).astype(str)

    temp[bin_col] = temp[bin_col].replace("nan", "NaN").fillna("NaN")

    return slice_auc_report(
        temp,
        col=bin_col,
        target_col=target_col,
        pred_col=pred_col,
        min_count=min_count,
        top_n=50,
    )

================================================================================
Slice: 시술 시기 코드

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
6,시술 시기 코드,TRZKPL,35544,9068,26476,0.255120,0.494128,0.239008,0.724789,0.266968
2,시술 시기 코드,TRJXFG,36031,9594,26437,0.266271,0.514627,0.248356,0.727333,0.282896
4,시술 시기 코드,TRXQMD,34831,8921,25910,0.256122,0.490376,0.234254,0.727659,0.265446
3,시술 시기 코드,TRVNRY,36173,9397,26776,0.259779,0.503665,0.243885,0.728418,0.275126
5,시술 시기 코드,TRYBLT,36713,9879,26834,0.269087,0.519180,0.250093,0.740738,0.294623
0,시술 시기 코드,TRCMWS,38090,9805,28285,0.257417,0.497704,0.240287,0.759202,0.307546
1,시술 시기 코드,TRDQAZ,38969,9564,29405,0.245426,0.481219,0.235793,0.767976,0.310950

================================================================================
Slice: 시술 유형

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
0,시술 유형,DI,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038
1,시술 유형,IVF,250060,65417,184643,0.261605,0.506303,0.244698,0.738864,0.287975

================================================================================
Slice: 특정 시술 유형

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
2,특정 시술 유형,ICSI / BLASTOCYST,1609,574,1035,0.356743,0.686063,0.329320,0.644350,0.235520
9,특정 시술 유형,Unknown,26939,6390,20549,0.237203,0.444176,0.206973,0.656616,0.172311
1,특정 시술 유형,ICSI / AH,769,167,602,0.217165,0.408653,0.191488,0.670838,0.190198
7,특정 시술 유형,IVF / BLASTOCYST,1248,457,791,0.366186,0.648905,0.282719,0.683961,0.248187
5,특정 시술 유형,IUI,6100,784,5316,0.128525,0.249689,0.121164,0.684120,0.101224
0,특정 시술 유형,ICSI,122368,33385,88983,0.272825,0.527726,0.254901,0.731333,0.288463
6,특정 시술 유형,IVF,91755,23990,67765,0.261457,0.510081,0.248624,0.752311,0.302611
4,특정 시술 유형,ICSI:IVF,873,205,668,0.234822,0.465558,0.230736,0.838740,0.336021
8,특정 시술 유형,IVF:IVF,1146,12,1134,0.010471,0.056884,0.046413,0.939521,0.075888
3,특정 시술 유형,ICSI:ICSI,2314,23,2291,0.009939,0.061858,0.051918,0.945135,0.098715

================================================================================
Slice: 배란 유도 유형

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
1,배란 유도 유형,알 수 없음,61917,14040,47877,0.226755,0.431287,0.204532,0.710674,0.225443
0,배란 유도 유형,기록되지 않은 시행,194432,52187,142245,0.268407,0.521885,0.253478,0.745400,0.301496

================================================================================
Slice: 배란 자극 여부

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
0,배란 자극 여부,0,58631,13582,45049,0.231652,0.441433,0.209781,0.708282,0.226171
1,배란 자극 여부,1,197720,52646,145074,0.266265,0.517370,0.251104,0.746458,0.301275

================================================================================
Slice: 시술 당시 나이

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
1,시술 당시 나이,만35-37세,57780,16086,41694,0.278401,0.539338,0.260937,0.702349,0.260992
0,시술 당시 나이,만18-34세,102476,33061,69415,0.322622,0.621649,0.299027,0.704089,0.285486
2,시술 당시 나이,만38-39세,39247,8522,30725,0.217138,0.414971,0.197833,0.710201,0.225007
3,시술 당시 나이,만40-42세,37348,5953,31395,0.159393,0.305565,0.146172,0.737779,0.196063
4,시술 당시 나이,만43-44세,12253,1446,10807,0.118012,0.255738,0.137726,0.829624,0.232119
5,시술 당시 나이,만45-50세,6918,1160,5758,0.167679,0.357340,0.189661,0.833020,0.290704

================================================================================
Slice: 난자 출처

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
0,난자 출처,기증 제공,15769,4974,10795,0.315429,0.604024,0.288595,0.682562,0.250394
2,난자 출처,알 수 없음,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038
1,난자 출처,본인 제공,234291,60443,173848,0.257983,0.499726,0.241744,0.742112,0.289147

================================================================================
Slice: 정자 출처

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
1,정자 출처,배우자 제공,229199,59630,169569,0.260167,0.504052,0.243885,0.739435,0.288336
0,정자 출처,기증 제공,27016,6585,20431,0.243744,0.466906,0.223162,0.749585,0.278869

================================================================================
Slice: 난자 기증자 나이

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
2,난자 기증자 나이,만31-35세,6366,1943,4423,0.305215,0.596870,0.291655,0.670852,0.246755
1,난자 기증자 나이,만26-30세,4976,1733,3243,0.348272,0.640814,0.292543,0.678621,0.255231
0,난자 기증자 나이,만21-25세,2334,770,1564,0.329906,0.610597,0.280692,0.710745,0.259542
3,난자 기증자 나이,알 수 없음,242381,61705,180676,0.254579,0.493427,0.238848,0.743419,0.288106

================================================================================
Slice: 정자 기증자 나이

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
6,정자 기증자 나이,알 수 없음,230518,59927,170591,0.259967,0.503611,0.243644,0.739527,0.288243
5,정자 기증자 나이,만41-45세,3848,935,2913,0.242983,0.472885,0.229901,0.739694,0.269587
3,정자 기증자 나이,만31-35세,4911,1221,3690,0.248626,0.480162,0.231536,0.743219,0.280639
2,정자 기증자 나이,만26-30세,5058,1255,3803,0.248122,0.463131,0.215010,0.743357,0.282350
0,정자 기증자 나이,만20세 이하,1067,224,843,0.209934,0.420876,0.210942,0.748941,0.277257
4,정자 기증자 나이,만36-40세,5282,1298,3984,0.245740,0.475428,0.229688,0.758085,0.273759
1,정자 기증자 나이,만21-25세,5667,1368,4299,0.241398,0.459512,0.218114,0.760991,0.288891

================================================================================
Slice: 배아 생성 주요 이유

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
4,배아 생성 주요 이유,배아 저장용,9192,8,9184,0.000870,0.042063,0.041192,0.448688,0.026437
2,배아 생성 주요 이유,"기증용, 현재 시술용",3784,1437,2347,0.379757,0.709398,0.329642,0.671984,0.268099
0,배아 생성 주요 이유,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038
5,배아 생성 주요 이유,현재 시술용,233732,63942,169790,0.273570,0.527529,0.253959,0.719926,0.273973
3,배아 생성 주요 이유,난자 저장용,1959,0,1959,0.000000,0.056388,0.056388,NaN,0.023990
1,배아 생성 주요 이유,기증용,1108,0,1108,0.000000,0.054112,0.054112,NaN,0.032923

================================================================================
Slice: 신선 배아 사용 여부

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
0,신선 배아 사용 여부,0.0,39924,9166,30758,0.229586,0.429630,0.200043,0.653818,0.166171
2,신선 배아 사용 여부,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038
1,신선 배아 사용 여부,1.0,210136,56251,153885,0.267689,0.520871,0.253182,0.748025,0.303497

================================================================================
Slice: 동결 배아 사용 여부

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
1,동결 배아 사용 여부,1.0,40126,9205,30921,0.229402,0.429068,0.199666,0.654270,0.166247
2,동결 배아 사용 여부,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038
0,동결 배아 사용 여부,0.0,209934,56212,153722,0.267760,0.521066,0.253306,0.748011,0.303546

================================================================================
Slice: 기증 배아 사용 여부

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
1,기증 배아 사용 여부,1.0,2458,805,1653,0.327502,0.632679,0.305177,0.683346,0.231651
2,기증 배아 사용 여부,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038
0,기증 배아 사용 여부,0.0,247602,64612,182990,0.260951,0.505049,0.244098,0.739344,0.288202

================================================================================
Slice: 대리모 여부

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
1,대리모 여부,1.0,1049,303,746,0.288847,0.568480,0.279634,0.616803,0.198489
2,대리모 여부,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038
0,대리모 여부,0.0,249011,65114,183897,0.261490,0.506042,0.244551,0.739285,0.288265

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
45,배아 생성 주요 이유,배아 저장용,9192,8,9184,0.000870,0.042063,0.041192,0.448688,0.026437
60,대리모 여부,1.0,1049,303,746,0.288847,0.568480,0.279634,0.616803,0.198489
9,특정 시술 유형,ICSI / BLASTOCYST,1609,574,1035,0.356743,0.686063,0.329320,0.644350,0.235520
51,신선 배아 사용 여부,0.0,39924,9166,30758,0.229586,0.429630,0.200043,0.653818,0.166171
54,동결 배아 사용 여부,1.0,40126,9205,30921,0.229402,0.429068,0.199666,0.654270,0.166247
10,특정 시술 유형,Unknown,26939,6390,20549,0.237203,0.444176,0.206973,0.656616,0.172311
11,특정 시술 유형,ICSI / AH,769,167,602,0.217165,0.408653,0.191488,0.670838,0.190198
34,난자 기증자 나이,만31-35세,6366,1943,4423,0.305215,0.596870,0.291655,0.670852,0.246755
46,배아 생성 주요 이유,"기증용, 현재 시술용",3784,1437,2347,0.379757,0.709398,0.329642,0.671984,0.268099
35,난자 기증자 나이,만26-30세,4976,1733,3243,0.348272,0.640814,0.292543,0.678621,0.255231
29,난자 출처,기증 제공,15769,4974,10795,0.315429,0.604024,0.288595,0.682562,0.250394
57,기증 배아 사용 여부,1.0,2458,805,1653,0.327502,0.632679,0.305177,0.683346,0.231651
12,특정 시술 유형,IVF / BLASTOCYST,1248,457,791,0.366186,0.648905,0.282719,0.683961,0.248187
13,특정 시술 유형,IUI,6100,784,5316,0.128525,0.249689,0.121164,0.684120,0.101224
7,시술 유형,DI,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038
30,난자 출처,알 수 없음,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038
47,배아 생성 주요 이유,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038
52,신선 배아 사용 여부,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038
55,동결 배아 사용 여부,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038
58,기증 배아 사용 여부,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038
61,대리모 여부,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038
23,시술 당시 나이,만35-37세,57780,16086,41694,0.278401,0.539338,0.260937,0.702349,0.260992
24,시술 당시 나이,만18-34세,102476,33061,69415,0.322622,0.621649,0.299027,0.704089,0.285486
21,배란 자극 여부,0,58631,13582,45049,0.231652,0.441433,0.209781,0.708282,0.226171
25,시술 당시 나이,만38-39세,39247,8522,30725,0.217138,0.414971,0.197833,0.710201,0.225007
19,배란 유도 유형,알 수 없음,61917,14040,47877,0.226755,0.431287,0.204532,0.710674,0.225443
36,난자 기증자 나이,만21-25세,2334,770,1564,0.329906,0.610597,0.280692,0.710745,0.259542
48,배아 생성 주요 이유,현재 시술용,233732,63942,169790,0.273570,0.527529,0.253959,0.719926,0.273973
0,시술 시기 코드,TRZKPL,35544,9068,26476,0.255120,0.494128,0.239008,0.724789,0.266968
1,시술 시기 코드,TRJXFG,36031,9594,26437,0.266271,0.514627,0.248356,0.727333,0.282896
2,시술 시기 코드,TRXQMD,34831,8921,25910,0.256122,0.490376,0.234254,0.727659,0.265446
3,시술 시기 코드,TRVNRY,36173,9397,26776,0.259779,0.503665,0.243885,0.728418,0.275126
14,특정 시술 유형,ICSI,122368,33385,88983,0.272825,0.527726,0.254901,0.731333,0.288463
26,시술 당시 나이,만40-42세,37348,5953,31395,0.159393,0.305565,0.146172,0.737779,0.196063
8,시술 유형,IVF,250060,65417,184643,0.261605,0.506303,0.244698,0.738864,0.287975
62,대리모 여부,0.0,249011,65114,183897,0.261490,0.506042,0.244551,0.739285,0.288265
59,기증 배아 사용 여부,0.0,247602,64612,182990,0.260951,0.505049,0.244098,0.739344,0.288202
32,정자 출처,배우자 제공,229199,59630,169569,0.260167,0.504052,0.243885,0.739435,0.288336
38,정자 기증자 나이,알 수 없음,230518,59927,170591,0.259967,0.503611,0.243644,0.739527,0.288243
39,정자 기증자 나이,만41-45세,3848,935,2913,0.242983,0.472885,0.229901,0.739694,0.269587
4,시술 시기 코드,TRYBLT,36713,9879,26834,0.269087,0.519180,0.250093,0.740738,0.294623
31,난자 출처,본인 제공,234291,60443,173848,0.257983,0.499726,0.241744,0.742112,0.289147
40,정자 기증자 나이,만31-35세,4911,1221,3690,0.248626,0.480162,0.231536,0.743219,0.280639
41,정자 기증자 나이,만26-30세,5058,1255,3803,0.248122,0.463131,0.215010,0.743357,0.282350
37,난자 기증자 나이,알 수 없음,242381,61705,180676,0.254579,0.493427,0.238848,0.743419,0.288106
20,배란 유도 유형,기록되지 않은 시행,194432,52187,142245,0.268407,0.521885,0.253478,0.745400,0.301496
22,배란 자극 여부,1,197720,52646,145074,0.266265,0.517370,0.251104,0.746458,0.301275
56,동결 배아 사용 여부,0.0,209934,56212,153722,0.267760,0.521066,0.253306,0.748011,0.303546
53,신선 배아 사용 여부,1.0,210136,56251,153885,0.267689,0.520871,0.253182,0.748025,0.303497
42,정자 기증자 나이,만20세 이하,1067,224,843,0.209934,0.420876,0.210942,0.748941,0.277257

In [11]:
numeric_slice_cols = [
    "이식된 배아 수",
    "총 생성 배아 수",
    "저장된 배아 수",
    "해동된 배아 수",
    "수집된 신선 난자 수",
    "혼합된 난자 수",
    "미세주입된 난자 수",
    "파트너 정자와 혼합된 난자 수",
    "배아 이식 경과일",
    "배아 해동 경과일",
    "난자 혼합 경과일",
    "난자 해동 경과일",
    "총 시술 횟수",
    "IVF 시술 횟수",
    "DI 시술 횟수",
    "총 임신 횟수",
    "총 출산 횟수",
]

numeric_slice_cols += [
    col for col in engineered_slice_cols
    if col in analysis_df.columns
]

numeric_slice_cols = [
    col for col in numeric_slice_cols
    if col in analysis_df.columns
]

all_num_reports = []

for col in numeric_slice_cols:
    print("\n" + "=" * 80)
    print("Numeric Slice:", col)

    report = numeric_bin_report(
        analysis_df,
        col=col,
        bins=5,
        min_count=500,
    )

    display(report)

    if not report.empty:
        report["source_numeric_col"] = col
        all_num_reports.append(report)

num_report_df = pd.concat(all_num_reports, ignore_index=True)
num_report_df.to_csv(SAVE_DIR / "numeric_slice_auc_report.csv", index=False)

display(
    num_report_df.sort_values(
        ["auc", "count"],
        ascending=[True, False],
        na_position="last"
    ).head(50)
)

================================================================================
Numeric Slice: 이식된 배아 수

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
0,이식된 배아 수_bin,0.0,36544,30,36514,0.000821,0.071417,0.070596,0.550100,0.036001
2,이식된 배아 수_bin,2.0,110845,34483,76362,0.311092,0.586404,0.275312,0.655963,0.219070
3,이식된 배아 수_bin,3.0,8880,1496,7384,0.168468,0.305845,0.137376,0.666380,0.139728
1,이식된 배아 수_bin,1.0,93791,29408,64383,0.313548,0.600063,0.286515,0.684980,0.261081
4,이식된 배아 수_bin,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038

================================================================================
Numeric Slice: 총 생성 배아 수

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
2,총 생성 배아 수_bin,"(5.0, 9.0]",59403,20149,39254,0.339192,0.654290,0.315098,0.677120,0.262573
4,총 생성 배아 수_bin,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038
1,총 생성 배아 수_bin,"(3.0, 5.0]",42022,12227,29795,0.290967,0.561790,0.270824,0.686267,0.252476
3,총 생성 배아 수_bin,"(9.0, 51.0]",39921,13904,26017,0.348288,0.667119,0.318832,0.711014,0.315802
0,총 생성 배아 수_bin,"(-0.001, 3.0]",108714,19137,89577,0.176031,0.344940,0.168910,0.746377,0.207673

================================================================================
Numeric Slice: 저장된 배아 수

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
2,저장된 배아 수_bin,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038
0,저장된 배아 수_bin,"(-0.001, 2.0]",207111,51464,155647,0.248485,0.482132,0.233647,0.718414,0.258269
1,저장된 배아 수_bin,"(2.0, 51.0]",42949,13953,28996,0.324874,0.622863,0.297990,0.769515,0.380499

================================================================================
Numeric Slice: 해동된 배아 수

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
1,해동된 배아 수_bin,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038
0,해동된 배아 수_bin,"(-0.001, 32.0]",250060,65417,184643,0.261605,0.506303,0.244698,0.738864,0.287975

================================================================================
Numeric Slice: 수집된 신선 난자 수

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
4,수집된 신선 난자 수_bin,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038
1,수집된 신선 난자 수_bin,"(10.0, 14.0]",41832,13697,28135,0.327429,0.625866,0.298437,0.691778,0.272430
3,수집된 신선 난자 수_bin,"(6.0, 10.0]",52115,14479,37636,0.277828,0.538442,0.260614,0.712143,0.272574
2,수집된 신선 난자 수_bin,"(14.0, 51.0]",48690,15345,33345,0.315157,0.612046,0.296889,0.732422,0.322855
0,수집된 신선 난자 수_bin,"(-0.001, 6.0]",107423,21896,85527,0.203830,0.396224,0.192395,0.744309,0.240005

================================================================================
Numeric Slice: 혼합된 난자 수

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
4,혼합된 난자 수_bin,"(9.0, 13.0]",43496,14712,28784,0.338238,0.646546,0.308308,0.683138,0.268419
5,혼합된 난자 수_bin,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038
3,혼합된 난자 수_bin,"(5.0, 9.0]",61680,17858,43822,0.289527,0.560035,0.270509,0.703230,0.269458
2,혼합된 난자 수_bin,"(13.0, 51.0]",42671,13876,28795,0.325186,0.629220,0.304034,0.722236,0.317009
0,혼합된 난자 수_bin,"(-0.001, 1.0]",53100,9545,43555,0.179755,0.351555,0.171800,0.740883,0.201811
1,혼합된 난자 수_bin,"(1.0, 5.0]",49113,9426,39687,0.191925,0.375137,0.183212,0.755230,0.242146

================================================================================
Numeric Slice: 미세주입된 난자 수

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
3,미세주입된 난자 수_bin,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038
1,미세주입된 난자 수_bin,"(4.0, 9.0]",50410,14560,35850,0.288832,0.555211,0.266379,0.703651,0.268974
2,미세주입된 난자 수_bin,"(9.0, 51.0]",43616,14544,29072,0.333456,0.641121,0.307665,0.706044,0.296019
0,미세주입된 난자 수_bin,"(-0.001, 4.0]",156034,36313,119721,0.232725,0.452818,0.220093,0.750513,0.276265

================================================================================
Numeric Slice: 파트너 정자와 혼합된 난자 수

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
4,파트너 정자와 혼합된 난자 수_bin,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038
3,파트너 정자와 혼합된 난자 수_bin,"(8.0, 12.0]",45248,14788,30460,0.326821,0.629362,0.302541,0.687359,0.267370
2,파트너 정자와 혼합된 난자 수_bin,"(5.0, 8.0]",43788,12344,31444,0.281904,0.544642,0.262738,0.701974,0.266400
1,파트너 정자와 혼합된 난자 수_bin,"(12.0, 51.0]",47556,15679,31877,0.329696,0.635787,0.306091,0.713443,0.307795
0,파트너 정자와 혼합된 난자 수_bin,"(-0.001, 5.0]",113468,22606,90862,0.199228,0.388168,0.188940,0.754558,0.244075

================================================================================
Numeric Slice: 배아 이식 경과일

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
1,배아 이식 경과일_bin,1.0,6053,1132,4921,0.187015,0.370344,0.183330,0.606298,0.119561
0,배아 이식 경과일_bin,0.0,24904,6252,18652,0.251044,0.453350,0.202306,0.615225,0.143071
5,배아 이식 경과일_bin,5.0,81459,32946,48513,0.404449,0.767590,0.363141,0.619864,0.186849
6,배아 이식 경과일_bin,6.0,2773,832,1941,0.300036,0.587765,0.287729,0.624893,0.199201
4,배아 이식 경과일_bin,4.0,4504,1551,2953,0.344361,0.666717,0.322357,0.625448,0.185063
3,배아 이식 경과일_bin,3.0,57924,14989,42935,0.258770,0.494740,0.235970,0.656934,0.205637
2,배아 이식 경과일_bin,2.0,35078,7453,27625,0.212469,0.406952,0.194482,0.691498,0.197500
7,배아 이식 경과일_bin,NaN,43566,1036,42530,0.023780,0.103192,0.079412,0.942938,0.093277

================================================================================
Numeric Slice: 배아 해동 경과일

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
0,배아 해동 경과일_bin,0.0,39801,9141,30660,0.229668,0.429720,0.200052,0.653998,0.166080
1,배아 해동 경과일_bin,NaN,215982,56999,158983,0.263906,0.513497,0.249591,0.750147,0.302943

================================================================================
Numeric Slice: 난자 혼합 경과일

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
1,난자 혼합 경과일_bin,NaN,53735,10155,43580,0.188983,0.364300,0.175317,0.721915,0.194545
0,난자 혼합 경과일_bin,0.0,201920,55947,145973,0.277075,0.536544,0.259469,0.736036,0.297353

================================================================================
Numeric Slice: 난자 해동 경과일

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
1,난자 해동 경과일_bin,NaN,254915,65909,189006,0.258553,0.500293,0.241740,0.740587,0.287618
0,난자 해동 경과일_bin,0.0,1434,319,1115,0.222455,0.448676,0.226221,0.768559,0.282914

================================================================================
Numeric Slice: 총 시술 횟수

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
0,총 시술 횟수_bin,NaN,256351,66228,190123,0.258349,0.500002,0.241653,0.740771,0.287617

================================================================================
Numeric Slice: IVF 시술 횟수

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
0,IVF 시술 횟수_bin,NaN,256351,66228,190123,0.258349,0.500002,0.241653,0.740771,0.287617

================================================================================
Numeric Slice: DI 시술 횟수

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
0,DI 시술 횟수_bin,NaN,256351,66228,190123,0.258349,0.500002,0.241653,0.740771,0.287617

================================================================================
Numeric Slice: 총 임신 횟수

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
0,총 임신 횟수_bin,NaN,256351,66228,190123,0.258349,0.500002,0.241653,0.740771,0.287617

================================================================================
Numeric Slice: 총 출산 횟수

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
0,총 출산 횟수_bin,NaN,256351,66228,190123,0.258349,0.500002,0.241653,0.740771,0.287617

================================================================================
Numeric Slice: 배아_이식_집중도

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
1,배아_이식_집중도_bin,"(0.167, 0.667]",57172,24175,32997,0.422847,0.804224,0.381377,0.608740,0.163511
2,배아_이식_집중도_bin,"(0.667, 1.0]",147652,37163,110489,0.251693,0.477515,0.225822,0.657938,0.198239
0,배아_이식_집중도_bin,"(-0.001, 0.167]",51527,4890,46637,0.094902,0.226889,0.131987,0.939386,0.300916

================================================================================
Numeric Slice: 배아_생성률

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
2,배아_생성률_bin,"(0.688, 0.842]",51040,16520,34520,0.323668,0.624259,0.300591,0.697664,0.283898
1,배아_생성률_bin,"(0.5, 0.688]",45622,13578,32044,0.297620,0.571777,0.274157,0.707010,0.279948
3,배아_생성률_bin,"(0.842, 1.25]",51027,15412,35615,0.302036,0.579150,0.277114,0.731475,0.303977
0,배아_생성률_bin,"(-0.001, 0.5]",108662,20718,87944,0.190665,0.374334,0.183670,0.748325,0.229906

================================================================================
Numeric Slice: 배아_이식률

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
1,배아_이식률_bin,"(0.111, 0.25]",57534,22385,35149,0.389074,0.738783,0.349709,0.627238,0.188458
2,배아_이식률_bin,"(0.25, 0.5]",52879,16277,36602,0.307816,0.587119,0.279303,0.644432,0.210972
3,배아_이식률_bin,"(0.5, 3.0]",43235,7879,35356,0.182237,0.348335,0.166098,0.691327,0.170185
0,배아_이식률_bin,"(-0.001, 0.111]",102703,19687,83016,0.191689,0.385231,0.193542,0.815685,0.304587

================================================================================
Numeric Slice: 배아_냉동률

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
0,배아_냉동률_bin,"(-0.001, 0.3]",205320,50365,154955,0.24530,0.475878,0.230578,0.718120,0.255171
1,배아_냉동률_bin,"(0.3, 7.0]",51031,15863,35168,0.31085,0.597062,0.286212,0.775822,0.376593

================================================================================
Numeric Slice: IVF_임신성공률

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
0,IVF_임신성공률_bin,"(-0.001, 1.0]",256351,66228,190123,0.258349,0.500002,0.241653,0.740771,0.287617

================================================================================
Numeric Slice: DI_임신성공률

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
0,DI_임신성공률_bin,"(-0.001, 1.0]",256351,66228,190123,0.258349,0.500002,0.241653,0.740771,0.287617

================================================================================
Numeric Slice: 고령여부

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
0,고령여부_bin,0,160585,49147,111438,0.306050,0.590788,0.284739,0.707141,0.280643
1,고령여부_bin,1,95766,17081,78685,0.178362,0.347767,0.169405,0.755601,0.228851

================================================================================
Numeric Slice: 고령_난자수_interaction

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
1,고령_난자수_interaction_bin,"(4.0, 51.0]",48962,9459,39503,0.193191,0.370903,0.177713,0.725572,0.221896
0,고령_난자수_interaction_bin,"(-0.001, 4.0]",207389,56769,150620,0.273732,0.530481,0.256749,0.736518,0.292857

================================================================================
Numeric Slice: 출산_임신_전환율

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
2,출산_임신_전환율_bin,1.0,33714,9052,24662,0.268494,0.508995,0.240501,0.723813,0.265002
1,출산_임신_전환율_bin,0.5,3448,890,2558,0.258121,0.471854,0.213734,0.734241,0.252540
0,출산_임신_전환율_bin,0.0,218555,56136,162419,0.256851,0.499226,0.242375,0.743339,0.291528

================================================================================
Numeric Slice: 클리닉_집중도

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
0,클리닉_집중도_bin,"(-0.001, 1.0]",256351,66228,190123,0.258349,0.500002,0.241653,0.740771,0.287617

================================================================================
Numeric Slice: 배아 이식 경과일_performed

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
1,배아 이식 경과일_performed_bin,1,212785,65192,147593,0.306375,0.581246,0.274871,0.675002,0.242982
0,배아 이식 경과일_performed_bin,0,43566,1036,42530,0.023780,0.103192,0.079412,0.942938,0.093277

================================================================================
Numeric Slice: 배아 해동 경과일_performed

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
1,배아 해동 경과일_performed_bin,1,40369,9229,31140,0.228616,0.427800,0.199184,0.656018,0.167664
0,배아 해동 경과일_performed_bin,0,215982,56999,158983,0.263906,0.513497,0.249591,0.750147,0.302943

================================================================================
Numeric Slice: 난자 혼합 경과일_performed

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
0,난자 혼합 경과일_performed_bin,0,53735,10155,43580,0.188983,0.364300,0.175317,0.721915,0.194545
1,난자 혼합 경과일_performed_bin,1,202616,56073,146543,0.276745,0.535991,0.259246,0.736322,0.297399

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std,source_numeric_col
0,이식된 배아 수_bin,0.0,36544,30,36514,0.000821,0.071417,0.070596,0.550100,0.036001,이식된 배아 수
35,배아 이식 경과일_bin,1.0,6053,1132,4921,0.187015,0.370344,0.183330,0.606298,0.119561,배아 이식 경과일
54,배아_이식_집중도_bin,"(0.167, 0.667]",57172,24175,32997,0.422847,0.804224,0.381377,0.608740,0.163511,배아_이식_집중도
36,배아 이식 경과일_bin,0.0,24904,6252,18652,0.251044,0.453350,0.202306,0.615225,0.143071,배아 이식 경과일
37,배아 이식 경과일_bin,5.0,81459,32946,48513,0.404449,0.767590,0.363141,0.619864,0.186849,배아 이식 경과일
38,배아 이식 경과일_bin,6.0,2773,832,1941,0.300036,0.587765,0.287729,0.624893,0.199201,배아 이식 경과일
39,배아 이식 경과일_bin,4.0,4504,1551,2953,0.344361,0.666717,0.322357,0.625448,0.185063,배아 이식 경과일
61,배아_이식률_bin,"(0.111, 0.25]",57534,22385,35149,0.389074,0.738783,0.349709,0.627238,0.188458,배아_이식률
62,배아_이식률_bin,"(0.25, 0.5]",52879,16277,36602,0.307816,0.587119,0.279303,0.644432,0.210972,배아_이식률
43,배아 해동 경과일_bin,0.0,39801,9141,30660,0.229668,0.429720,0.200052,0.653998,0.166080,배아 해동 경과일
1,이식된 배아 수_bin,2.0,110845,34483,76362,0.311092,0.586404,0.275312,0.655963,0.219070,이식된 배아 수
79,배아 해동 경과일_performed_bin,1,40369,9229,31140,0.228616,0.427800,0.199184,0.656018,0.167664,배아 해동 경과일_performed
40,배아 이식 경과일_bin,3.0,57924,14989,42935,0.258770,0.494740,0.235970,0.656934,0.205637,배아 이식 경과일
55,배아_이식_집중도_bin,"(0.667, 1.0]",147652,37163,110489,0.251693,0.477515,0.225822,0.657938,0.198239,배아_이식_집중도
2,이식된 배아 수_bin,3.0,8880,1496,7384,0.168468,0.305845,0.137376,0.666380,0.139728,이식된 배아 수
77,배아 이식 경과일_performed_bin,1,212785,65192,147593,0.306375,0.581246,0.274871,0.675002,0.242982,배아 이식 경과일_performed
5,총 생성 배아 수_bin,"(5.0, 9.0]",59403,20149,39254,0.339192,0.654290,0.315098,0.677120,0.262573,총 생성 배아 수
20,혼합된 난자 수_bin,"(9.0, 13.0]",43496,14712,28784,0.338238,0.646546,0.308308,0.683138,0.268419,혼합된 난자 수
3,이식된 배아 수_bin,1.0,93791,29408,64383,0.313548,0.600063,0.286515,0.684980,0.261081,이식된 배아 수
4,이식된 배아 수_bin,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,이식된 배아 수
6,총 생성 배아 수_bin,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,총 생성 배아 수
10,저장된 배아 수_bin,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,저장된 배아 수
13,해동된 배아 수_bin,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,해동된 배아 수
15,수집된 신선 난자 수_bin,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,수집된 신선 난자 수
21,혼합된 난자 수_bin,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,혼합된 난자 수
26,미세주입된 난자 수_bin,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,미세주입된 난자 수
30,파트너 정자와 혼합된 난자 수_bin,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,파트너 정자와 혼합된 난자 수
7,총 생성 배아 수_bin,"(3.0, 5.0]",42022,12227,29795,0.290967,0.561790,0.270824,0.686267,0.252476,총 생성 배아 수
31,파트너 정자와 혼합된 난자 수_bin,"(8.0, 12.0]",45248,14788,30460,0.326821,0.629362,0.302541,0.687359,0.267370,파트너 정자와 혼합된 난자 수
63,배아_이식률_bin,"(0.5, 3.0]",43235,7879,35356,0.182237,0.348335,0.166098,0.691327,0.170185,배아_이식률
41,배아 이식 경과일_bin,2.0,35078,7453,27625,0.212469,0.406952,0.194482,0.691498,0.197500,배아 이식 경과일
16,수집된 신선 난자 수_bin,"(10.0, 14.0]",41832,13697,28135,0.327429,0.625866,0.298437,0.691778,0.272430,수집된 신선 난자 수
57,배아_생성률_bin,"(0.688, 0.842]",51040,16520,34520,0.323668,0.624259,0.300591,0.697664,0.283898,배아_생성률
32,파트너 정자와 혼합된 난자 수_bin,"(5.0, 8.0]",43788,12344,31444,0.281904,0.544642,0.262738,0.701974,0.266400,파트너 정자와 혼합된 난자 수
22,혼합된 난자 수_bin,"(5.0, 9.0]",61680,17858,43822,0.289527,0.560035,0.270509,0.703230,0.269458,혼합된 난자 수
27,미세주입된 난자 수_bin,"(4.0, 9.0]",50410,14560,35850,0.288832,0.555211,0.266379,0.703651,0.268974,미세주입된 난자 수
28,미세주입된 난자 수_bin,"(9.0, 51.0]",43616,14544,29072,0.333456,0.641121,0.307665,0.706044,0.296019,미세주입된 난자 수
58,배아_생성률_bin,"(0.5, 0.688]",45622,13578,32044,0.297620,0.571777,0.274157,0.707010,0.279948,배아_생성률
69,고령여부_bin,0,160585,49147,111438,0.306050,0.590788,0.284739,0.707141,0.280643,고령여부
8,총 생성 배아 수_bin,"(9.0, 51.0]",39921,13904,26017,0.348288,0.667119,0.318832,0.711014,0.315802,총 생성 배아 수
17,수집된 신선 난자 수_bin,"(6.0, 10.0]",52115,14479,37636,0.277828,0.538442,0.260614,0.712143,0.272574,수집된 신선 난자 수
33,파트너 정자와 혼합된 난자 수_bin,"(12.0, 51.0]",47556,15679,31877,0.329696,0.635787,0.306091,0.713443,0.307795,파트너 정자와 혼합된 난자 수
65,배아_냉동률_bin,"(-0.001, 0.3]",205320,50365,154955,0.245300,0.475878,0.230578,0.718120,0.255171,배아_냉동률
11,저장된 배아 수_bin,"(-0.001, 2.0]",207111,51464,155647,0.248485,0.482132,0.233647,0.718414,0.258269,저장된 배아 수
45,난자 혼합 경과일_bin,NaN,53735,10155,43580,0.188983,0.364300,0.175317,0.721915,0.194545,난자 혼합 경과일
81,난자 혼합 경과일_performed_bin,0,53735,10155,43580,0.188983,0.364300,0.175317,0.721915,0.194545,난자 혼합 경과일_performed
23,혼합된 난자 수_bin,"(13.0, 51.0]",42671,13876,28795,0.325186,0.629220,0.304034,0.722236,0.317009,혼합된 난자 수
73,출산_임신_전환율_bin,1.0,33714,9052,24662,0.268494,0.508995,0.240501,0.723813,0.265002,출산_임신_전환율
71,고령_난자수_interaction_bin,"(4.0, 51.0]",48962,9459,39503,0.193191,0.370903,0.177713,0.725572,0.221896,고령_난자수_interaction
59,배아_생성률_bin,"(0.842, 1.25]",51027,15412,35615,0.302036,0.579150,0.277114,0.731475,0.303977,배아_생성률

In [12]:
all_slice_df = pd.concat(
    [cat_report_df, num_report_df],
    ignore_index=True
)

all_slice_df["abs_calibration_gap"] = all_slice_df["calibration_gap"].abs()

all_slice_df.to_csv(SAVE_DIR / "all_slice_report.csv", index=False)

print("AUC 낮은 slice")
display(
    all_slice_df.sort_values(
        ["auc", "count"],
        ascending=[True, False],
        na_position="last"
    ).head(50)
)

print("Calibration gap 큰 slice")
display(
    all_slice_df.sort_values(
        ["abs_calibration_gap", "count"],
        ascending=[False, False],
        na_position="last"
    ).head(50)
)

AUC 낮은 slice

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std,source_numeric_col,abs_calibration_gap
45,배아 생성 주요 이유,배아 저장용,9192,8,9184,0.000870,0.042063,0.041192,0.448688,0.026437,NaN,0.041192
63,이식된 배아 수_bin,0.0,36544,30,36514,0.000821,0.071417,0.070596,0.550100,0.036001,이식된 배아 수,0.070596
98,배아 이식 경과일_bin,1.0,6053,1132,4921,0.187015,0.370344,0.183330,0.606298,0.119561,배아 이식 경과일,0.183330
117,배아_이식_집중도_bin,"(0.167, 0.667]",57172,24175,32997,0.422847,0.804224,0.381377,0.608740,0.163511,배아_이식_집중도,0.381377
99,배아 이식 경과일_bin,0.0,24904,6252,18652,0.251044,0.453350,0.202306,0.615225,0.143071,배아 이식 경과일,0.202306
60,대리모 여부,1.0,1049,303,746,0.288847,0.568480,0.279634,0.616803,0.198489,NaN,0.279634
100,배아 이식 경과일_bin,5.0,81459,32946,48513,0.404449,0.767590,0.363141,0.619864,0.186849,배아 이식 경과일,0.363141
101,배아 이식 경과일_bin,6.0,2773,832,1941,0.300036,0.587765,0.287729,0.624893,0.199201,배아 이식 경과일,0.287729
102,배아 이식 경과일_bin,4.0,4504,1551,2953,0.344361,0.666717,0.322357,0.625448,0.185063,배아 이식 경과일,0.322357
124,배아_이식률_bin,"(0.111, 0.25]",57534,22385,35149,0.389074,0.738783,0.349709,0.627238,0.188458,배아_이식률,0.349709
9,특정 시술 유형,ICSI / BLASTOCYST,1609,574,1035,0.356743,0.686063,0.329320,0.644350,0.235520,NaN,0.329320
125,배아_이식률_bin,"(0.25, 0.5]",52879,16277,36602,0.307816,0.587119,0.279303,0.644432,0.210972,배아_이식률,0.279303
51,신선 배아 사용 여부,0.0,39924,9166,30758,0.229586,0.429630,0.200043,0.653818,0.166171,NaN,0.200043
106,배아 해동 경과일_bin,0.0,39801,9141,30660,0.229668,0.429720,0.200052,0.653998,0.166080,배아 해동 경과일,0.200052
54,동결 배아 사용 여부,1.0,40126,9205,30921,0.229402,0.429068,0.199666,0.654270,0.166247,NaN,0.199666
64,이식된 배아 수_bin,2.0,110845,34483,76362,0.311092,0.586404,0.275312,0.655963,0.219070,이식된 배아 수,0.275312
142,배아 해동 경과일_performed_bin,1,40369,9229,31140,0.228616,0.427800,0.199184,0.656018,0.167664,배아 해동 경과일_performed,0.199184
10,특정 시술 유형,Unknown,26939,6390,20549,0.237203,0.444176,0.206973,0.656616,0.172311,NaN,0.206973
103,배아 이식 경과일_bin,3.0,57924,14989,42935,0.258770,0.494740,0.235970,0.656934,0.205637,배아 이식 경과일,0.235970
118,배아_이식_집중도_bin,"(0.667, 1.0]",147652,37163,110489,0.251693,0.477515,0.225822,0.657938,0.198239,배아_이식_집중도,0.225822
65,이식된 배아 수_bin,3.0,8880,1496,7384,0.168468,0.305845,0.137376,0.666380,0.139728,이식된 배아 수,0.137376
11,특정 시술 유형,ICSI / AH,769,167,602,0.217165,0.408653,0.191488,0.670838,0.190198,NaN,0.191488
34,난자 기증자 나이,만31-35세,6366,1943,4423,0.305215,0.596870,0.291655,0.670852,0.246755,NaN,0.291655
46,배아 생성 주요 이유,"기증용, 현재 시술용",3784,1437,2347,0.379757,0.709398,0.329642,0.671984,0.268099,NaN,0.329642
140,배아 이식 경과일_performed_bin,1,212785,65192,147593,0.306375,0.581246,0.274871,0.675002,0.242982,배아 이식 경과일_performed,0.274871
68,총 생성 배아 수_bin,"(5.0, 9.0]",59403,20149,39254,0.339192,0.654290,0.315098,0.677120,0.262573,총 생성 배아 수,0.315098
35,난자 기증자 나이,만26-30세,4976,1733,3243,0.348272,0.640814,0.292543,0.678621,0.255231,NaN,0.292543
29,난자 출처,기증 제공,15769,4974,10795,0.315429,0.604024,0.288595,0.682562,0.250394,NaN,0.288595
83,혼합된 난자 수_bin,"(9.0, 13.0]",43496,14712,28784,0.338238,0.646546,0.308308,0.683138,0.268419,혼합된 난자 수,0.308308
57,기증 배아 사용 여부,1.0,2458,805,1653,0.327502,0.632679,0.305177,0.683346,0.231651,NaN,0.305177
12,특정 시술 유형,IVF / BLASTOCYST,1248,457,791,0.366186,0.648905,0.282719,0.683961,0.248187,NaN,0.282719
13,특정 시술 유형,IUI,6100,784,5316,0.128525,0.249689,0.121164,0.684120,0.101224,NaN,0.121164
66,이식된 배아 수_bin,1.0,93791,29408,64383,0.313548,0.600063,0.286515,0.684980,0.261081,이식된 배아 수,0.286515
7,시술 유형,DI,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,NaN,0.120610
30,난자 출처,알 수 없음,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,NaN,0.120610
47,배아 생성 주요 이유,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,NaN,0.120610
52,신선 배아 사용 여부,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,NaN,0.120610
55,동결 배아 사용 여부,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,NaN,0.120610
58,기증 배아 사용 여부,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,NaN,0.120610
61,대리모 여부,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,NaN,0.120610
67,이식된 배아 수_bin,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,이식된 배아 수,0.120610
69,총 생성 배아 수_bin,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,총 생성 배아 수,0.120610
73,저장된 배아 수_bin,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,저장된 배아 수,0.120610
76,해동된 배아 수_bin,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,해동된 배아 수,0.120610
78,수집된 신선 난자 수_bin,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,수집된 신선 난자 수,0.120610
84,혼합된 난자 수_bin,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,혼합된 난자 수,0.120610
89,미세주입된 난자 수_bin,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,미세주입된 난자 수,0.120610
93,파트너 정자와 혼합된 난자 수_bin,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,파트너 정자와 혼합된 난자 수,0.120610
70,총 생성 배아 수_bin,"(3.0, 5.0]",42022,12227,29795,0.290967,0.561790,0.270824,0.686267,0.252476,총 생성 배아 수,0.270824
94,파트너 정자와 혼합된 난자 수_bin,"(8.0, 12.0]",45248,14788,30460,0.326821,0.629362,0.302541,0.687359,0.267370,파트너 정자와 혼합된 난자 수,0.302541

Calibration gap 큰 slice

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std,source_numeric_col,abs_calibration_gap
117,배아_이식_집중도_bin,"(0.167, 0.667]",57172,24175,32997,0.422847,0.804224,0.381377,0.608740,0.163511,배아_이식_집중도,0.381377
100,배아 이식 경과일_bin,5.0,81459,32946,48513,0.404449,0.767590,0.363141,0.619864,0.186849,배아 이식 경과일,0.363141
124,배아_이식률_bin,"(0.111, 0.25]",57534,22385,35149,0.389074,0.738783,0.349709,0.627238,0.188458,배아_이식률,0.349709
46,배아 생성 주요 이유,"기증용, 현재 시술용",3784,1437,2347,0.379757,0.709398,0.329642,0.671984,0.268099,NaN,0.329642
9,특정 시술 유형,ICSI / BLASTOCYST,1609,574,1035,0.356743,0.686063,0.329320,0.644350,0.235520,NaN,0.329320
102,배아 이식 경과일_bin,4.0,4504,1551,2953,0.344361,0.666717,0.322357,0.625448,0.185063,배아 이식 경과일,0.322357
71,총 생성 배아 수_bin,"(9.0, 51.0]",39921,13904,26017,0.348288,0.667119,0.318832,0.711014,0.315802,총 생성 배아 수,0.318832
68,총 생성 배아 수_bin,"(5.0, 9.0]",59403,20149,39254,0.339192,0.654290,0.315098,0.677120,0.262573,총 생성 배아 수,0.315098
83,혼합된 난자 수_bin,"(9.0, 13.0]",43496,14712,28784,0.338238,0.646546,0.308308,0.683138,0.268419,혼합된 난자 수,0.308308
91,미세주입된 난자 수_bin,"(9.0, 51.0]",43616,14544,29072,0.333456,0.641121,0.307665,0.706044,0.296019,미세주입된 난자 수,0.307665
96,파트너 정자와 혼합된 난자 수_bin,"(12.0, 51.0]",47556,15679,31877,0.329696,0.635787,0.306091,0.713443,0.307795,파트너 정자와 혼합된 난자 수,0.306091
57,기증 배아 사용 여부,1.0,2458,805,1653,0.327502,0.632679,0.305177,0.683346,0.231651,NaN,0.305177
86,혼합된 난자 수_bin,"(13.0, 51.0]",42671,13876,28795,0.325186,0.629220,0.304034,0.722236,0.317009,혼합된 난자 수,0.304034
94,파트너 정자와 혼합된 난자 수_bin,"(8.0, 12.0]",45248,14788,30460,0.326821,0.629362,0.302541,0.687359,0.267370,파트너 정자와 혼합된 난자 수,0.302541
120,배아_생성률_bin,"(0.688, 0.842]",51040,16520,34520,0.323668,0.624259,0.300591,0.697664,0.283898,배아_생성률,0.300591
24,시술 당시 나이,만18-34세,102476,33061,69415,0.322622,0.621649,0.299027,0.704089,0.285486,NaN,0.299027
79,수집된 신선 난자 수_bin,"(10.0, 14.0]",41832,13697,28135,0.327429,0.625866,0.298437,0.691778,0.272430,수집된 신선 난자 수,0.298437
75,저장된 배아 수_bin,"(2.0, 51.0]",42949,13953,28996,0.324874,0.622863,0.297990,0.769515,0.380499,저장된 배아 수,0.297990
81,수집된 신선 난자 수_bin,"(14.0, 51.0]",48690,15345,33345,0.315157,0.612046,0.296889,0.732422,0.322855,수집된 신선 난자 수,0.296889
35,난자 기증자 나이,만26-30세,4976,1733,3243,0.348272,0.640814,0.292543,0.678621,0.255231,NaN,0.292543
34,난자 기증자 나이,만31-35세,6366,1943,4423,0.305215,0.596870,0.291655,0.670852,0.246755,NaN,0.291655
29,난자 출처,기증 제공,15769,4974,10795,0.315429,0.604024,0.288595,0.682562,0.250394,NaN,0.288595
101,배아 이식 경과일_bin,6.0,2773,832,1941,0.300036,0.587765,0.287729,0.624893,0.199201,배아 이식 경과일,0.287729
66,이식된 배아 수_bin,1.0,93791,29408,64383,0.313548,0.600063,0.286515,0.684980,0.261081,이식된 배아 수,0.286515
129,배아_냉동률_bin,"(0.3, 7.0]",51031,15863,35168,0.310850,0.597062,0.286212,0.775822,0.376593,배아_냉동률,0.286212
132,고령여부_bin,0,160585,49147,111438,0.306050,0.590788,0.284739,0.707141,0.280643,고령여부,0.284739
12,특정 시술 유형,IVF / BLASTOCYST,1248,457,791,0.366186,0.648905,0.282719,0.683961,0.248187,NaN,0.282719
36,난자 기증자 나이,만21-25세,2334,770,1564,0.329906,0.610597,0.280692,0.710745,0.259542,NaN,0.280692
60,대리모 여부,1.0,1049,303,746,0.288847,0.568480,0.279634,0.616803,0.198489,NaN,0.279634
125,배아_이식률_bin,"(0.25, 0.5]",52879,16277,36602,0.307816,0.587119,0.279303,0.644432,0.210972,배아_이식률,0.279303
122,배아_생성률_bin,"(0.842, 1.25]",51027,15412,35615,0.302036,0.579150,0.277114,0.731475,0.303977,배아_생성률,0.277114
64,이식된 배아 수_bin,2.0,110845,34483,76362,0.311092,0.586404,0.275312,0.655963,0.219070,이식된 배아 수,0.275312
140,배아 이식 경과일_performed_bin,1,212785,65192,147593,0.306375,0.581246,0.274871,0.675002,0.242982,배아 이식 경과일_performed,0.274871
121,배아_생성률_bin,"(0.5, 0.688]",45622,13578,32044,0.297620,0.571777,0.274157,0.707010,0.279948,배아_생성률,0.274157
70,총 생성 배아 수_bin,"(3.0, 5.0]",42022,12227,29795,0.290967,0.561790,0.270824,0.686267,0.252476,총 생성 배아 수,0.270824
85,혼합된 난자 수_bin,"(5.0, 9.0]",61680,17858,43822,0.289527,0.560035,0.270509,0.703230,0.269458,혼합된 난자 수,0.270509
90,미세주입된 난자 수_bin,"(4.0, 9.0]",50410,14560,35850,0.288832,0.555211,0.266379,0.703651,0.268974,미세주입된 난자 수,0.266379
95,파트너 정자와 혼합된 난자 수_bin,"(5.0, 8.0]",43788,12344,31444,0.281904,0.544642,0.262738,0.701974,0.266400,파트너 정자와 혼합된 난자 수,0.262738
23,시술 당시 나이,만35-37세,57780,16086,41694,0.278401,0.539338,0.260937,0.702349,0.260992,NaN,0.260937
80,수집된 신선 난자 수_bin,"(6.0, 10.0]",52115,14479,37636,0.277828,0.538442,0.260614,0.712143,0.272574,수집된 신선 난자 수,0.260614
109,난자 혼합 경과일_bin,0.0,201920,55947,145973,0.277075,0.536544,0.259469,0.736036,0.297353,난자 혼합 경과일,0.259469
145,난자 혼합 경과일_performed_bin,1,202616,56073,146543,0.276745,0.535991,0.259246,0.736322,0.297399,난자 혼합 경과일_performed,0.259246
135,고령_난자수_interaction_bin,"(-0.001, 4.0]",207389,56769,150620,0.273732,0.530481,0.256749,0.736518,0.292857,고령_난자수_interaction,0.256749
14,특정 시술 유형,ICSI,122368,33385,88983,0.272825,0.527726,0.254901,0.731333,0.288463,NaN,0.254901
48,배아 생성 주요 이유,현재 시술용,233732,63942,169790,0.273570,0.527529,0.253959,0.719926,0.273973,NaN,0.253959
20,배란 유도 유형,기록되지 않은 시행,194432,52187,142245,0.268407,0.521885,0.253478,0.745400,0.301496,NaN,0.253478
56,동결 배아 사용 여부,0.0,209934,56212,153722,0.267760,0.521066,0.253306,0.748011,0.303546,NaN,0.253306
53,신선 배아 사용 여부,1.0,210136,56251,153885,0.267689,0.520871,0.253182,0.748025,0.303497,NaN,0.253182
22,배란 자극 여부,1,197720,52646,145074,0.266265,0.517370,0.251104,0.746458,0.301275,NaN,0.251104
4,시술 시기 코드,TRYBLT,36713,9879,26834,0.269087,0.519180,0.250093,0.740738,0.294623,NaN,0.250093

In [13]:
def add_pair_combo(df, col1, col2):
    combo_name = f"{col1}__x__{col2}"
    df[combo_name] = df[col1].astype(str) + "__" + df[col2].astype(str)
    return combo_name


pair_cols = [
    ("시술 당시 나이", "난자 출처"),
    ("시술 당시 나이", "시술 유형"),
    ("시술 당시 나이", "특정 시술 유형"),
    ("시술 유형", "난자 출처"),
    ("시술 유형", "정자 출처"),
    ("난자 출처", "정자 출처"),
    ("시술 유형", "배아 생성 주요 이유"),
    ("시술 당시 나이", "배아 생성 주요 이유"),
]

pair_reports = []

for col1, col2 in pair_cols:
    if col1 not in analysis_df.columns or col2 not in analysis_df.columns:
        continue

    combo_col = add_pair_combo(analysis_df, col1, col2)

    print("\n" + "=" * 80)
    print("Pair Slice:", combo_col)

    report = slice_auc_report(
        analysis_df,
        col=combo_col,
        min_count=500,
        top_n=50,
    )

    display(report)

    if not report.empty:
        pair_reports.append(report)

pair_report_df = pd.concat(pair_reports, ignore_index=True)
pair_report_df.to_csv(SAVE_DIR / "pair_slice_auc_report.csv", index=False)

display(
    pair_report_df.sort_values(
        ["auc", "count"],
        ascending=[True, False],
        na_position="last"
    ).head(50)
)

================================================================================
Pair Slice: 시술 당시 나이__x__난자 출처

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
8,시술 당시 나이__x__난자 출처,만38-39세__알 수 없음,1053,108,945,0.102564,0.209079,0.106515,0.540849,0.038561
2,시술 당시 나이__x__난자 출처,만18-34세__알 수 없음,2071,403,1668,0.194592,0.326186,0.131594,0.591422,0.108857
5,시술 당시 나이__x__난자 출처,만35-37세__알 수 없음,1450,219,1231,0.151034,0.272573,0.121538,0.613901,0.081315
11,시술 당시 나이__x__난자 출처,만40-42세__알 수 없음,1036,72,964,0.069498,0.174440,0.104942,0.627622,0.020815
0,시술 당시 나이__x__난자 출처,만18-34세__기증 제공,2871,880,1991,0.306513,0.617108,0.310594,0.665797,0.238441
12,시술 당시 나이__x__난자 출처,만43-44세__기증 제공,2459,837,1622,0.340382,0.631100,0.290718,0.667978,0.257793
3,시술 당시 나이__x__난자 출처,만35-37세__기증 제공,1869,594,1275,0.317817,0.603854,0.286037,0.677184,0.250966
14,시술 당시 나이__x__난자 출처,만45-50세__기증 제공,3679,1075,2604,0.292199,0.565240,0.273041,0.685464,0.249755
6,시술 당시 나이__x__난자 출처,만38-39세__기증 제공,1619,525,1094,0.324274,0.604799,0.280525,0.686917,0.245488
9,시술 당시 나이__x__난자 출처,만40-42세__기증 제공,3272,1063,2209,0.324878,0.615519,0.290642,0.699801,0.252916
4,시술 당시 나이__x__난자 출처,만35-37세__본인 제공,54461,15273,39188,0.280439,0.544227,0.263788,0.700879,0.260519
1,시술 당시 나이__x__난자 출처,만18-34세__본인 제공,97534,31778,65756,0.325815,0.628057,0.302242,0.703639,0.286029
7,시술 당시 나이__x__난자 출처,만38-39세__본인 제공,36575,7889,28686,0.215694,0.412496,0.196802,0.706041,0.220899
10,시술 당시 나이__x__난자 출처,만40-42세__본인 제공,33040,4818,28222,0.145823,0.278981,0.133158,0.721512,0.162316
13,시술 당시 나이__x__난자 출처,만43-44세__본인 제공,9375,601,8774,0.064107,0.162214,0.098107,0.751552,0.082111
15,시술 당시 나이__x__난자 출처,만45-50세__본인 제공,2977,84,2893,0.028216,0.119372,0.091155,0.840794,0.071860

================================================================================
Pair Slice: 시술 당시 나이__x__시술 유형

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
4,시술 당시 나이__x__시술 유형,만38-39세__DI,1053,108,945,0.102564,0.209079,0.106515,0.540849,0.038561
0,시술 당시 나이__x__시술 유형,만18-34세__DI,2071,403,1668,0.194592,0.326186,0.131594,0.591422,0.108857
2,시술 당시 나이__x__시술 유형,만35-37세__DI,1450,219,1231,0.151034,0.272573,0.121538,0.613901,0.081315
6,시술 당시 나이__x__시술 유형,만40-42세__DI,1036,72,964,0.069498,0.174440,0.104942,0.627622,0.020815
3,시술 당시 나이__x__시술 유형,만35-37세__IVF,56330,15867,40463,0.281679,0.546205,0.264526,0.700213,0.260425
1,시술 당시 나이__x__시술 유형,만18-34세__IVF,100405,32658,67747,0.325263,0.627744,0.302481,0.702743,0.284783
5,시술 당시 나이__x__시술 유형,만38-39세__IVF,38194,8414,29780,0.220296,0.420648,0.200351,0.707669,0.225349
7,시술 당시 나이__x__시술 유형,만40-42세__IVF,36312,5881,30431,0.161957,0.309306,0.147348,0.735787,0.197537
9,시술 당시 나이__x__시술 유형,만45-50세__IVF,6656,1159,5497,0.174129,0.365818,0.191690,0.825803,0.293151
8,시술 당시 나이__x__시술 유형,만43-44세__IVF,11834,1438,10396,0.121514,0.259644,0.138130,0.826452,0.235245

================================================================================
Pair Slice: 시술 당시 나이__x__특정 시술 유형

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
13,시술 당시 나이__x__특정 시술 유형,만38-39세__IUI,1031,105,926,0.101843,0.209585,0.107742,0.548853,0.038710
3,시술 당시 나이__x__특정 시술 유형,만18-34세__IUI,1976,383,1593,0.193826,0.327971,0.134145,0.587864,0.108959
9,시술 당시 나이__x__특정 시술 유형,만35-37세__IUI,1411,215,1196,0.152374,0.273238,0.120864,0.609835,0.081431
1,시술 당시 나이__x__특정 시술 유형,만18-34세__ICSI / BLASTOCYST,928,365,563,0.393319,0.760588,0.367269,0.616871,0.198722
17,시술 당시 나이__x__특정 시술 유형,만40-42세__IUI,1016,72,944,0.070866,0.174654,0.103788,0.624058,0.020882
5,시술 당시 나이__x__특정 시술 유형,만18-34세__IVF / BLASTOCYST,655,282,373,0.430534,0.742814,0.312279,0.630293,0.217408
19,시술 당시 나이__x__특정 시술 유형,만40-42세__Unknown,4497,898,3599,0.199689,0.366658,0.166969,0.635374,0.135150
11,시술 당시 나이__x__특정 시술 유형,만35-37세__Unknown,6282,1596,4686,0.254059,0.469780,0.215721,0.638181,0.160950
15,시술 당시 나이__x__특정 시술 유형,만38-39세__Unknown,4433,987,3446,0.222648,0.414842,0.192194,0.644650,0.147088
7,시술 당시 나이__x__특정 시술 유형,만18-34세__Unknown,8643,2319,6324,0.268310,0.511741,0.243432,0.649026,0.177650
25,시술 당시 나이__x__특정 시술 유형,만45-50세__Unknown,1389,274,1115,0.197264,0.375360,0.178096,0.669494,0.164244
0,시술 당시 나이__x__특정 시술 유형,만18-34세__ICSI,52401,17852,34549,0.340681,0.655927,0.315247,0.686389,0.270365
8,시술 당시 나이__x__특정 시술 유형,만35-37세__ICSI,27185,7861,19324,0.289167,0.561775,0.272608,0.692773,0.256197
12,시술 당시 나이__x__특정 시술 유형,만38-39세__ICSI,18080,4033,14047,0.223064,0.420814,0.197750,0.700157,0.224424
22,시술 당시 나이__x__특정 시술 유형,만43-44세__Unknown,1694,316,1378,0.186541,0.343713,0.157172,0.700182,0.173000
4,시술 당시 나이__x__특정 시술 유형,만18-34세__IVF,35273,11640,23633,0.329997,0.639462,0.309464,0.708584,0.296863
10,시술 당시 나이__x__특정 시술 유형,만35-37세__IVF,21013,6024,14989,0.286680,0.561583,0.274904,0.708809,0.273911
14,시술 당시 나이__x__특정 시술 유형,만38-39세__IVF,14377,3150,11227,0.219100,0.428431,0.209331,0.727228,0.240404
16,시술 당시 나이__x__특정 시술 유형,만40-42세__ICSI,16791,2621,14170,0.156096,0.300212,0.144117,0.738776,0.198441
18,시술 당시 나이__x__특정 시술 유형,만40-42세__IVF,13773,2211,11562,0.160531,0.308348,0.147816,0.752074,0.208813
2,시술 당시 나이__x__특정 시술 유형,만18-34세__ICSI:ICSI,1178,6,1172,0.005093,0.057519,0.052426,0.827787,0.088206
20,시술 당시 나이__x__특정 시술 유형,만43-44세__ICSI,5173,585,4588,0.113087,0.254250,0.141163,0.832776,0.242721
21,시술 당시 나이__x__특정 시술 유형,만43-44세__IVF,4612,523,4089,0.113400,0.242709,0.129309,0.842215,0.241719
24,시술 당시 나이__x__특정 시술 유형,만45-50세__IVF,2397,442,1955,0.184397,0.382451,0.198054,0.844346,0.334626
23,시술 당시 나이__x__특정 시술 유형,만45-50세__ICSI,2727,433,2294,0.158783,0.355209,0.196427,0.851714,0.304112
6,시술 당시 나이__x__특정 시술 유형,만18-34세__IVF:IVF,550,4,546,0.007273,0.051498,0.044225,0.997253,0.056962

================================================================================
Pair Slice: 시술 유형__x__난자 출처

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
1,시술 유형__x__난자 출처,IVF__기증 제공,15769,4974,10795,0.315429,0.604024,0.288595,0.682562,0.250394
0,시술 유형__x__난자 출처,DI__알 수 없음,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038
2,시술 유형__x__난자 출처,IVF__본인 제공,234291,60443,173848,0.257983,0.499726,0.241744,0.742112,0.289147

================================================================================
Pair Slice: 시술 유형__x__정자 출처

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
0,시술 유형__x__정자 출처,DI__기증 제공,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038
1,시술 유형__x__정자 출처,IVF__기증 제공,20725,5774,14951,0.278601,0.532892,0.254291,0.730873,0.282095
2,시술 유형__x__정자 출처,IVF__배우자 제공,229199,59630,169569,0.260167,0.504052,0.243885,0.739435,0.288336

================================================================================
Pair Slice: 난자 출처__x__정자 출처

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
0,난자 출처__x__정자 출처,기증 제공__기증 제공,3368,1056,2312,0.313539,0.610159,0.296620,0.677693,0.230604
1,난자 출처__x__정자 출처,기증 제공__배우자 제공,12387,3916,8471,0.316138,0.602491,0.286354,0.683977,0.255492
4,난자 출처__x__정자 출처,알 수 없음__기증 제공,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038
2,난자 출처__x__정자 출처,본인 제공__기증 제공,17357,4718,12639,0.271821,0.517899,0.246078,0.740676,0.288652
3,난자 출처__x__정자 출처,본인 제공__배우자 제공,216812,55714,161098,0.256969,0.498428,0.241459,0.742086,0.289090

================================================================================
Pair Slice: 시술 유형__x__배아 생성 주요 이유

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
3,시술 유형__x__배아 생성 주요 이유,IVF__배아 저장용,9192,8,9184,0.000870,0.042063,0.041192,0.448688,0.026437
1,시술 유형__x__배아 생성 주요 이유,"IVF__기증용, 현재 시술용",3784,1437,2347,0.379757,0.709398,0.329642,0.671984,0.268099
5,시술 유형__x__배아 생성 주요 이유,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038
4,시술 유형__x__배아 생성 주요 이유,IVF__현재 시술용,233732,63942,169790,0.273570,0.527529,0.253959,0.719926,0.273973
2,시술 유형__x__배아 생성 주요 이유,IVF__난자 저장용,1959,0,1959,0.000000,0.056388,0.056388,NaN,0.023990
0,시술 유형__x__배아 생성 주요 이유,IVF__기증용,1108,0,1108,0.000000,0.054112,0.054112,NaN,0.032923

================================================================================
Pair Slice: 시술 당시 나이__x__배아 생성 주요 이유

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
3,시술 당시 나이__x__배아 생성 주요 이유,만18-34세__배아 저장용,3169,4,3165,0.001262,0.048917,0.047654,0.100632,0.019672
8,시술 당시 나이__x__배아 생성 주요 이유,만38-39세__배아 저장용,1249,1,1248,0.000801,0.043962,0.043161,0.491186,0.024774
1,시술 당시 나이__x__배아 생성 주요 이유,"만18-34세__기증용, 현재 시술용",3280,1279,2001,0.389939,0.725741,0.335802,0.660888,0.264857
7,시술 당시 나이__x__배아 생성 주요 이유,만35-37세__현재 시술용,53233,15705,37528,0.295024,0.569439,0.274415,0.679152,0.242461
4,시술 당시 나이__x__배아 생성 주요 이유,만18-34세__현재 시술용,92805,31358,61447,0.337891,0.650697,0.312806,0.682889,0.262984
0,시술 당시 나이__x__배아 생성 주요 이유,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038
9,시술 당시 나이__x__배아 생성 주요 이유,만38-39세__현재 시술용,36416,8410,28006,0.230942,0.438658,0.207716,0.689473,0.214859
11,시술 당시 나이__x__배아 생성 주요 이유,만40-42세__현재 시술용,34113,5875,28238,0.172222,0.327128,0.154906,0.715532,0.190225
12,시술 당시 나이__x__배아 생성 주요 이유,만43-44세__배아 저장용,743,2,741,0.002692,0.031836,0.029145,0.738192,0.032456
14,시술 당시 나이__x__배아 생성 주요 이유,만45-50세__현재 시술용,6202,1159,5043,0.186875,0.390336,0.203460,0.810150,0.288632
13,시술 당시 나이__x__배아 생성 주요 이유,만43-44세__현재 시술용,10963,1435,9528,0.130895,0.277760,0.146865,0.811724,0.234869
10,시술 당시 나이__x__배아 생성 주요 이유,만40-42세__배아 저장용,1753,1,1752,0.000570,0.028898,0.028328,0.839612,0.028421
6,시술 당시 나이__x__배아 생성 주요 이유,만35-37세__배아 저장용,1881,0,1881,0.000000,0.047721,0.047721,NaN,0.024057
2,시술 당시 나이__x__배아 생성 주요 이유,만18-34세__난자 저장용,530,0,530,0.000000,0.066090,0.066090,NaN,0.012619
5,시술 당시 나이__x__배아 생성 주요 이유,만35-37세__난자 저장용,504,0,504,0.000000,0.078238,0.078238,NaN,0.010224

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
69,시술 당시 나이__x__배아 생성 주요 이유,만18-34세__배아 저장용,3169,4,3165,0.001262,0.048917,0.047654,0.100632,0.019672
63,시술 유형__x__배아 생성 주요 이유,IVF__배아 저장용,9192,8,9184,0.000870,0.042063,0.041192,0.448688,0.026437
70,시술 당시 나이__x__배아 생성 주요 이유,만38-39세__배아 저장용,1249,1,1248,0.000801,0.043962,0.043161,0.491186,0.024774
0,시술 당시 나이__x__난자 출처,만38-39세__알 수 없음,1053,108,945,0.102564,0.209079,0.106515,0.540849,0.038561
16,시술 당시 나이__x__시술 유형,만38-39세__DI,1053,108,945,0.102564,0.209079,0.106515,0.540849,0.038561
26,시술 당시 나이__x__특정 시술 유형,만38-39세__IUI,1031,105,926,0.101843,0.209585,0.107742,0.548853,0.038710
27,시술 당시 나이__x__특정 시술 유형,만18-34세__IUI,1976,383,1593,0.193826,0.327971,0.134145,0.587864,0.108959
1,시술 당시 나이__x__난자 출처,만18-34세__알 수 없음,2071,403,1668,0.194592,0.326186,0.131594,0.591422,0.108857
17,시술 당시 나이__x__시술 유형,만18-34세__DI,2071,403,1668,0.194592,0.326186,0.131594,0.591422,0.108857
28,시술 당시 나이__x__특정 시술 유형,만35-37세__IUI,1411,215,1196,0.152374,0.273238,0.120864,0.609835,0.081431
2,시술 당시 나이__x__난자 출처,만35-37세__알 수 없음,1450,219,1231,0.151034,0.272573,0.121538,0.613901,0.081315
18,시술 당시 나이__x__시술 유형,만35-37세__DI,1450,219,1231,0.151034,0.272573,0.121538,0.613901,0.081315
29,시술 당시 나이__x__특정 시술 유형,만18-34세__ICSI / BLASTOCYST,928,365,563,0.393319,0.760588,0.367269,0.616871,0.198722
30,시술 당시 나이__x__특정 시술 유형,만40-42세__IUI,1016,72,944,0.070866,0.174654,0.103788,0.624058,0.020882
3,시술 당시 나이__x__난자 출처,만40-42세__알 수 없음,1036,72,964,0.069498,0.174440,0.104942,0.627622,0.020815
19,시술 당시 나이__x__시술 유형,만40-42세__DI,1036,72,964,0.069498,0.174440,0.104942,0.627622,0.020815
31,시술 당시 나이__x__특정 시술 유형,만18-34세__IVF / BLASTOCYST,655,282,373,0.430534,0.742814,0.312279,0.630293,0.217408
32,시술 당시 나이__x__특정 시술 유형,만40-42세__Unknown,4497,898,3599,0.199689,0.366658,0.166969,0.635374,0.135150
33,시술 당시 나이__x__특정 시술 유형,만35-37세__Unknown,6282,1596,4686,0.254059,0.469780,0.215721,0.638181,0.160950
34,시술 당시 나이__x__특정 시술 유형,만38-39세__Unknown,4433,987,3446,0.222648,0.414842,0.192194,0.644650,0.147088
35,시술 당시 나이__x__특정 시술 유형,만18-34세__Unknown,8643,2319,6324,0.268310,0.511741,0.243432,0.649026,0.177650
71,시술 당시 나이__x__배아 생성 주요 이유,"만18-34세__기증용, 현재 시술용",3280,1279,2001,0.389939,0.725741,0.335802,0.660888,0.264857
4,시술 당시 나이__x__난자 출처,만18-34세__기증 제공,2871,880,1991,0.306513,0.617108,0.310594,0.665797,0.238441
5,시술 당시 나이__x__난자 출처,만43-44세__기증 제공,2459,837,1622,0.340382,0.631100,0.290718,0.667978,0.257793
36,시술 당시 나이__x__특정 시술 유형,만45-50세__Unknown,1389,274,1115,0.197264,0.375360,0.178096,0.669494,0.164244
64,시술 유형__x__배아 생성 주요 이유,"IVF__기증용, 현재 시술용",3784,1437,2347,0.379757,0.709398,0.329642,0.671984,0.268099
6,시술 당시 나이__x__난자 출처,만35-37세__기증 제공,1869,594,1275,0.317817,0.603854,0.286037,0.677184,0.250966
58,난자 출처__x__정자 출처,기증 제공__기증 제공,3368,1056,2312,0.313539,0.610159,0.296620,0.677693,0.230604
72,시술 당시 나이__x__배아 생성 주요 이유,만35-37세__현재 시술용,53233,15705,37528,0.295024,0.569439,0.274415,0.679152,0.242461
52,시술 유형__x__난자 출처,IVF__기증 제공,15769,4974,10795,0.315429,0.604024,0.288595,0.682562,0.250394
73,시술 당시 나이__x__배아 생성 주요 이유,만18-34세__현재 시술용,92805,31358,61447,0.337891,0.650697,0.312806,0.682889,0.262984
59,난자 출처__x__정자 출처,기증 제공__배우자 제공,12387,3916,8471,0.316138,0.602491,0.286354,0.683977,0.255492
7,시술 당시 나이__x__난자 출처,만45-50세__기증 제공,3679,1075,2604,0.292199,0.565240,0.273041,0.685464,0.249755
53,시술 유형__x__난자 출처,DI__알 수 없음,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038
55,시술 유형__x__정자 출처,DI__기증 제공,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038
60,난자 출처__x__정자 출처,알 수 없음__기증 제공,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038
65,시술 유형__x__배아 생성 주요 이유,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038
74,시술 당시 나이__x__배아 생성 주요 이유,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038
37,시술 당시 나이__x__특정 시술 유형,만18-34세__ICSI,52401,17852,34549,0.340681,0.655927,0.315247,0.686389,0.270365
8,시술 당시 나이__x__난자 출처,만38-39세__기증 제공,1619,525,1094,0.324274,0.604799,0.280525,0.686917,0.245488
75,시술 당시 나이__x__배아 생성 주요 이유,만38-39세__현재 시술용,36416,8410,28006,0.230942,0.438658,0.207716,0.689473,0.214859
38,시술 당시 나이__x__특정 시술 유형,만35-37세__ICSI,27185,7861,19324,0.289167,0.561775,0.272608,0.692773,0.256197
9,시술 당시 나이__x__난자 출처,만40-42세__기증 제공,3272,1063,2209,0.324878,0.615519,0.290642,0.699801,0.252916
39,시술 당시 나이__x__특정 시술 유형,만38-39세__ICSI,18080,4033,14047,0.223064,0.420814,0.197750,0.700157,0.224424
40,시술 당시 나이__x__특정 시술 유형,만43-44세__Unknown,1694,316,1378,0.186541,0.343713,0.157172,0.700182,0.173000
20,시술 당시 나이__x__시술 유형,만35-37세__IVF,56330,15867,40463,0.281679,0.546205,0.264526,0.700213,0.260425
10,시술 당시 나이__x__난자 출처,만35-37세__본인 제공,54461,15273,39188,0.280439,0.544227,0.263788,0.700879,0.260519
21,시술 당시 나이__x__시술 유형,만18-34세__IVF,100405,32658,67747,0.325263,0.627744,0.302481,0.702743,0.284783
11,시술 당시 나이__x__난자 출처,만18-34세__본인 제공,97534,31778,65756,0.325815,0.628057,0.302242,0.703639,0.286029
12,시술 당시 나이__x__난자 출처,만38-39세__본인 제공,36575,7889,28686,0.215694,0.412496,0.196802,0.706041,0.220899

In [14]:
# 실제 1인데 낮게 예측한 케이스
false_negative_like = analysis_df[
    analysis_df["target"] == 1
].sort_values("pred", ascending=True)

# 실제 0인데 높게 예측한 케이스
false_positive_like = analysis_df[
    analysis_df["target"] == 0
].sort_values("pred", ascending=False)

cols_to_view = [
    "target",
    "pred",
    "pred_rank",
    "시술 유형",
    "특정 시술 유형",
    "시술 당시 나이",
    "난자 출처",
    "정자 출처",
    "배아 생성 주요 이유",
    "이식된 배아 수",
    "총 생성 배아 수",
    "저장된 배아 수",
    "수집된 신선 난자 수",
    "배아 이식 경과일",
]

cols_to_view = [col for col in cols_to_view if col in analysis_df.columns]

print("실제 성공인데 낮게 예측한 샘플")
display(false_negative_like[cols_to_view].head(30))

print("실제 실패인데 높게 예측한 샘플")
display(false_positive_like[cols_to_view].head(30))

false_negative_like[cols_to_view].head(200).to_csv(
    SAVE_DIR / "false_negative_like_top200.csv",
    index=False
)

false_positive_like[cols_to_view].head(200).to_csv(
    SAVE_DIR / "false_positive_like_top200.csv",
    index=False
)

실제 성공인데 낮게 예측한 샘플

,target,pred,pred_rank,시술 유형,특정 시술 유형,시술 당시 나이,난자 출처,정자 출처,배아 생성 주요 이유,이식된 배아 수,총 생성 배아 수,저장된 배아 수,수집된 신선 난자 수,배아 이식 경과일
102235,1,0.012556,0.006807,IVF,ICSI,만43-44세,본인 제공,배우자 제공,현재 시술용,0.0,0.0,0.0,4.0,NaN
49578,1,0.016360,0.009487,IVF,ICSI:ICSI,만18-34세,본인 제공,배우자 제공,배아 저장용,0.0,15.0,9.0,18.0,NaN
212604,1,0.017479,0.010294,IVF,ICSI,만43-44세,본인 제공,기증 제공,배아 저장용,0.0,7.0,2.0,12.0,NaN
78940,1,0.024081,0.015666,IVF,ICSI,만38-39세,본인 제공,배우자 제공,현재 시술용,0.0,6.0,6.0,16.0,NaN
107763,1,0.024969,0.016450,IVF,ICSI,만18-34세,본인 제공,배우자 제공,배아 저장용,0.0,6.0,5.0,8.0,NaN
116444,1,0.028499,0.019793,IVF,ICSI,만18-34세,본인 제공,배우자 제공,배아 저장용,0.0,14.0,11.0,23.0,NaN
227626,1,0.033403,0.024747,IVF,ICSI,만18-34세,본인 제공,배우자 제공,배아 저장용,0.0,9.0,9.0,19.0,NaN
55659,1,0.035111,0.026741,IVF,IVF:IVF,만38-39세,본인 제공,배우자 제공,배아 저장용,0.0,11.0,2.0,20.0,NaN
136155,1,0.045120,0.038724,IVF,ICSI,만38-39세,본인 제공,배우자 제공,현재 시술용,0.0,5.0,3.0,11.0,NaN
57176,1,0.052889,0.048188,IVF,ICSI,만35-37세,본인 제공,배우자 제공,현재 시술용,0.0,5.0,1.0,8.0,NaN
39990,1,0.057607,0.054246,IVF,ICSI,만40-42세,기증 제공,배우자 제공,배아 저장용,0.0,6.0,2.0,0.0,NaN
84661,1,0.061497,0.059348,IVF,IVF,만18-34세,본인 제공,배우자 제공,현재 시술용,0.0,15.0,15.0,22.0,NaN
62814,1,0.065577,0.064751,IVF,ICSI,만40-42세,본인 제공,배우자 제공,현재 시술용,0.0,6.0,0.0,10.0,NaN
26272,1,0.075005,0.077055,IVF,ICSI,만18-34세,본인 제공,배우자 제공,현재 시술용,0.0,0.0,0.0,8.0,NaN
66924,1,0.081785,0.085367,IVF,ICSI,만38-39세,본인 제공,배우자 제공,현재 시술용,0.0,2.0,0.0,3.0,NaN
185428,1,0.082956,0.086932,IVF,IVF,만35-37세,본인 제공,기증 제공,현재 시술용,0.0,27.0,10.0,29.0,NaN
82324,1,0.086203,0.090762,IVF,ICSI,만18-34세,본인 제공,배우자 제공,현재 시술용,0.0,4.0,0.0,16.0,NaN
216638,1,0.094760,0.100195,IVF,ICSI,만18-34세,본인 제공,배우자 제공,현재 시술용,0.0,13.0,2.0,14.0,NaN
244318,1,0.102178,0.108632,IVF,ICSI,만18-34세,본인 제공,배우자 제공,현재 시술용,0.0,2.0,0.0,5.0,NaN
128585,1,0.104356,0.111109,IVF,IVF,만18-34세,본인 제공,기증 제공,현재 시술용,0.0,11.0,11.0,24.0,NaN
77071,1,0.112924,0.120163,IVF,ICSI,만43-44세,기증 제공,기증 제공,배아 저장용,0.0,7.0,2.0,0.0,NaN
175899,1,0.115776,0.122941,IVF,IVF,만40-42세,본인 제공,배우자 제공,현재 시술용,0.0,0.0,0.0,0.0,NaN
90035,1,0.116157,0.123272,IVF,IVF:IVF,만45-50세,기증 제공,기증 제공,현재 시술용,0.0,6.0,5.0,0.0,NaN
6265,1,0.116720,0.123783,IVF,ICSI,만18-34세,본인 제공,배우자 제공,현재 시술용,0.0,5.0,0.0,6.0,NaN
136371,1,0.118838,0.125749,IVF,IVF,만38-39세,본인 제공,배우자 제공,현재 시술용,0.0,0.0,0.0,0.0,NaN
12694,1,0.124506,0.130645,IVF,IVF,만35-37세,본인 제공,배우자 제공,현재 시술용,0.0,0.0,0.0,0.0,NaN
117779,1,0.125017,0.131090,IVF,IVF,만45-50세,기증 제공,배우자 제공,현재 시술용,0.0,11.0,0.0,0.0,NaN
114803,1,0.128715,0.134472,IVF,IVF,만18-34세,본인 제공,배우자 제공,"기증용, 현재 시술용",0.0,8.0,0.0,19.0,NaN
195707,1,0.138150,0.141267,IVF,ICSI,만45-50세,본인 제공,배우자 제공,현재 시술용,1.0,1.0,0.0,3.0,2.0
146088,1,0.139118,0.141934,IVF,IVF,만45-50세,본인 제공,배우자 제공,현재 시술용,1.0,1.0,0.0,1.0,2.0

실제 실패인데 높게 예측한 샘플

,target,pred,pred_rank,시술 유형,특정 시술 유형,시술 당시 나이,난자 출처,정자 출처,배아 생성 주요 이유,이식된 배아 수,총 생성 배아 수,저장된 배아 수,수집된 신선 난자 수,배아 이식 경과일
117522,0,0.999936,0.999977,IVF,ICSI,만18-34세,본인 제공,배우자 제공,현재 시술용,2.0,10.0,6.0,17.0,5.0
61327,0,0.999934,0.999973,IVF,ICSI / BLASTOCYST,만18-34세,본인 제공,배우자 제공,현재 시술용,2.0,11.0,5.0,11.0,5.0
242223,0,0.999894,0.999965,IVF,ICSI,만35-37세,본인 제공,배우자 제공,현재 시술용,2.0,15.0,4.0,17.0,5.0
149996,0,0.999894,0.999961,IVF,IVF,만18-34세,본인 제공,배우자 제공,현재 시술용,2.0,18.0,5.0,19.0,5.0
181485,0,0.999807,0.999926,IVF,ICSI,만18-34세,본인 제공,배우자 제공,"기증용, 현재 시술용",2.0,7.0,4.0,19.0,5.0
146842,0,0.999806,0.999922,IVF,ICSI,만18-34세,본인 제공,배우자 제공,현재 시술용,2.0,14.0,3.0,17.0,5.0
104443,0,0.999798,0.999914,IVF,IVF,만18-34세,본인 제공,기증 제공,현재 시술용,2.0,8.0,2.0,10.0,5.0
145517,0,0.999759,0.999883,IVF,ICSI,만18-34세,본인 제공,배우자 제공,"기증용, 현재 시술용",2.0,7.0,3.0,15.0,5.0
183247,0,0.999735,0.999856,IVF,ICSI,만18-34세,본인 제공,배우자 제공,현재 시술용,2.0,20.0,12.0,24.0,5.0
196789,0,0.999731,0.999848,IVF,ICSI,만18-34세,본인 제공,배우자 제공,현재 시술용,2.0,15.0,6.0,17.0,5.0
236986,0,0.999718,0.999844,IVF,IVF,만18-34세,본인 제공,배우자 제공,"기증용, 현재 시술용",2.0,11.0,3.0,24.0,5.0
38296,0,0.999707,0.999836,IVF,ICSI,만18-34세,본인 제공,배우자 제공,현재 시술용,2.0,10.0,3.0,17.0,5.0
123749,0,0.999705,0.999832,IVF,ICSI,만18-34세,본인 제공,배우자 제공,현재 시술용,2.0,7.0,2.0,17.0,5.0
5632,0,0.999686,0.999809,IVF,ICSI,만35-37세,본인 제공,배우자 제공,현재 시술용,2.0,12.0,5.0,15.0,5.0
49542,0,0.999683,0.999805,IVF,IVF,만35-37세,본인 제공,배우자 제공,현재 시술용,2.0,10.0,4.0,13.0,5.0
175310,0,0.999649,0.999778,IVF,IVF,만18-34세,본인 제공,배우자 제공,현재 시술용,2.0,16.0,3.0,24.0,5.0
34093,0,0.999623,0.999762,IVF,ICSI,만18-34세,본인 제공,배우자 제공,현재 시술용,2.0,12.0,2.0,15.0,5.0
154396,0,0.999615,0.999754,IVF,IVF,만18-34세,본인 제공,배우자 제공,현재 시술용,2.0,9.0,3.0,14.0,5.0
20642,0,0.999611,0.999746,IVF,ICSI,만18-34세,본인 제공,배우자 제공,현재 시술용,2.0,6.0,3.0,9.0,5.0
251714,0,0.999587,0.999739,IVF,ICSI,만18-34세,본인 제공,배우자 제공,현재 시술용,2.0,10.0,5.0,17.0,5.0
120192,0,0.999568,0.999715,IVF,ICSI,만35-37세,본인 제공,배우자 제공,현재 시술용,2.0,15.0,6.0,19.0,5.0
236023,0,0.999558,0.999707,IVF,IVF,만18-34세,본인 제공,배우자 제공,현재 시술용,2.0,16.0,4.0,24.0,5.0
35585,0,0.999545,0.999700,IVF,IVF,만35-37세,본인 제공,기증 제공,현재 시술용,2.0,11.0,7.0,13.0,5.0
18072,0,0.999521,0.999684,IVF,IVF,만18-34세,본인 제공,배우자 제공,현재 시술용,2.0,9.0,2.0,11.0,5.0
34676,0,0.999510,0.999668,IVF,IVF,만35-37세,본인 제공,배우자 제공,현재 시술용,2.0,14.0,6.0,19.0,5.0
202162,0,0.999465,0.999622,IVF,IVF,만35-37세,본인 제공,배우자 제공,현재 시술용,2.0,12.0,4.0,14.0,5.0
52350,0,0.999464,0.999618,IVF,ICSI,만35-37세,본인 제공,배우자 제공,현재 시술용,2.0,13.0,4.0,20.0,5.0
165686,0,0.999455,0.999614,IVF,ICSI,만18-34세,본인 제공,배우자 제공,현재 시술용,2.0,10.0,4.0,18.0,5.0
103392,0,0.999443,0.999594,IVF,ICSI,만35-37세,본인 제공,배우자 제공,현재 시술용,2.0,11.0,4.0,16.0,5.0
220895,0,0.999412,0.999575,IVF,ICSI,만18-34세,본인 제공,배우자 제공,현재 시술용,2.0,10.0,3.0,15.0,5.0

In [15]:
candidate_slices = all_slice_df.copy()

candidate_slices = candidate_slices[
    (candidate_slices["count"] >= 1000) &
    (candidate_slices["auc"].notna())
].copy()

candidate_slices["weakness_score"] = (
    (0.7407705075 - candidate_slices["auc"]) *
    np.log1p(candidate_slices["count"])
)

candidate_slices = candidate_slices.sort_values(
    "weakness_score",
    ascending=False
)

display(candidate_slices.head(50))

candidate_slices.to_csv(
    SAVE_DIR / "candidate_weak_slices.csv",
    index=False
)

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std,source_numeric_col,abs_calibration_gap,weakness_score
45,배아 생성 주요 이유,배아 저장용,9192,8,9184,0.000870,0.042063,0.041192,0.448688,0.026437,NaN,0.041192,2.665603
63,이식된 배아 수_bin,0.0,36544,30,36514,0.000821,0.071417,0.070596,0.550100,0.036001,이식된 배아 수,0.070596,2.003237
117,배아_이식_집중도_bin,"(0.167, 0.667]",57172,24175,32997,0.422847,0.804224,0.381377,0.608740,0.163511,배아_이식_집중도,0.381377,1.446244
100,배아 이식 경과일_bin,5.0,81459,32946,48513,0.404449,0.767590,0.363141,0.619864,0.186849,배아 이식 경과일,0.363141,1.367197
99,배아 이식 경과일_bin,0.0,24904,6252,18652,0.251044,0.453350,0.202306,0.615225,0.143071,배아 이식 경과일,0.202306,1.270877
124,배아_이식률_bin,"(0.111, 0.25]",57534,22385,35149,0.389074,0.738783,0.349709,0.627238,0.188458,배아_이식률,0.349709,1.244329
98,배아 이식 경과일_bin,1.0,6053,1132,4921,0.187015,0.370344,0.183330,0.606298,0.119561,배아 이식 경과일,0.183330,1.171051
125,배아_이식률_bin,"(0.25, 0.5]",52879,16277,36602,0.307816,0.587119,0.279303,0.644432,0.210972,배아_이식률,0.279303,1.047760
118,배아_이식_집중도_bin,"(0.667, 1.0]",147652,37163,110489,0.251693,0.477515,0.225822,0.657938,0.198239,배아_이식_집중도,0.225822,0.985919
64,이식된 배아 수_bin,2.0,110845,34483,76362,0.311092,0.586404,0.275312,0.655963,0.219070,이식된 배아 수,0.275312,0.985113
102,배아 이식 경과일_bin,4.0,4504,1551,2953,0.344361,0.666717,0.322357,0.625448,0.185063,배아 이식 경과일,0.322357,0.970204
51,신선 배아 사용 여부,0.0,39924,9166,30758,0.229586,0.429630,0.200043,0.653818,0.166171,NaN,0.200043,0.921237
103,배아 이식 경과일_bin,3.0,57924,14989,42935,0.258770,0.494740,0.235970,0.656934,0.205637,배아 이식 경과일,0.235970,0.919426
106,배아 해동 경과일_bin,0.0,39801,9141,30660,0.229668,0.429720,0.200052,0.653998,0.166080,배아 해동 경과일,0.200052,0.919071
101,배아 이식 경과일_bin,6.0,2773,832,1941,0.300036,0.587765,0.287729,0.624893,0.199201,배아 이식 경과일,0.287729,0.918683
54,동결 배아 사용 여부,1.0,40126,9205,30921,0.229402,0.429068,0.199666,0.654270,0.166247,NaN,0.199666,0.916892
142,배아 해동 경과일_performed_bin,1,40369,9229,31140,0.228616,0.427800,0.199184,0.656018,0.167664,배아 해동 경과일_performed,0.199184,0.898871
60,대리모 여부,1.0,1049,303,746,0.288847,0.568480,0.279634,0.616803,0.198489,NaN,0.279634,0.862383
10,특정 시술 유형,Unknown,26939,6390,20549,0.237203,0.444176,0.206973,0.656616,0.172311,NaN,0.206973,0.858493
140,배아 이식 경과일_performed_bin,1,212785,65192,147593,0.306375,0.581246,0.274871,0.675002,0.242982,배아 이식 경과일_performed,0.274871,0.806849
9,특정 시술 유형,ICSI / BLASTOCYST,1609,574,1035,0.356743,0.686063,0.329320,0.644350,0.235520,NaN,0.329320,0.711967
68,총 생성 배아 수_bin,"(5.0, 9.0]",59403,20149,39254,0.339192,0.654290,0.315098,0.677120,0.262573,총 생성 배아 수,0.315098,0.699651
65,이식된 배아 수_bin,3.0,8880,1496,7384,0.168468,0.305845,0.137376,0.666380,0.139728,이식된 배아 수,0.137376,0.676338
66,이식된 배아 수_bin,1.0,93791,29408,64383,0.313548,0.600063,0.286515,0.684980,0.261081,이식된 배아 수,0.286515,0.638738
83,혼합된 난자 수_bin,"(9.0, 13.0]",43496,14712,28784,0.338238,0.646546,0.308308,0.683138,0.268419,혼합된 난자 수,0.308308,0.615546
34,난자 기증자 나이,만31-35세,6366,1943,4423,0.305215,0.596870,0.291655,0.670852,0.246755,NaN,0.291655,0.612406
70,총 생성 배아 수_bin,"(3.0, 5.0]",42022,12227,29795,0.290967,0.561790,0.270824,0.686267,0.252476,총 생성 배아 수,0.270824,0.580242
94,파트너 정자와 혼합된 난자 수_bin,"(8.0, 12.0]",45248,14788,30460,0.326821,0.629362,0.302541,0.687359,0.267370,파트너 정자와 혼합된 난자 수,0.302541,0.572566
46,배아 생성 주요 이유,"기증용, 현재 시술용",3784,1437,2347,0.379757,0.709398,0.329642,0.671984,0.268099,NaN,0.329642,0.566715
29,난자 출처,기증 제공,15769,4974,10795,0.315429,0.604024,0.288595,0.682562,0.250394,NaN,0.288595,0.562631
35,난자 기증자 나이,만26-30세,4976,1733,3243,0.348272,0.640814,0.292543,0.678621,0.255231,NaN,0.292543,0.529052
126,배아_이식률_bin,"(0.5, 3.0]",43235,7879,35356,0.182237,0.348335,0.166098,0.691327,0.170185,배아_이식률,0.166098,0.527779
79,수집된 신선 난자 수_bin,"(10.0, 14.0]",41832,13697,28135,0.327429,0.625866,0.298437,0.691778,0.272430,수집된 신선 난자 수,0.298437,0.521355
104,배아 이식 경과일_bin,2.0,35078,7453,27625,0.212469,0.406952,0.194482,0.691498,0.197500,배아 이식 경과일,0.194482,0.515653
13,특정 시술 유형,IUI,6100,784,5316,0.128525,0.249689,0.121164,0.684120,0.101224,NaN,0.121164,0.493776
52,신선 배아 사용 여부,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,NaN,0.120610,0.480217
61,대리모 여부,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,NaN,0.120610,0.480217
55,동결 배아 사용 여부,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,NaN,0.120610,0.480217
67,이식된 배아 수_bin,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,이식된 배아 수,0.120610,0.480217
76,해동된 배아 수_bin,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,해동된 배아 수,0.120610,0.480217
7,시술 유형,DI,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,NaN,0.120610,0.480217
58,기증 배아 사용 여부,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,NaN,0.120610,0.480217
69,총 생성 배아 수_bin,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,총 생성 배아 수,0.120610,0.480217
73,저장된 배아 수_bin,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,저장된 배아 수,0.120610,0.480217
47,배아 생성 주요 이유,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,NaN,0.120610,0.480217
78,수집된 신선 난자 수_bin,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,수집된 신선 난자 수,0.120610,0.480217
84,혼합된 난자 수_bin,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,혼합된 난자 수,0.120610,0.480217
89,미세주입된 난자 수_bin,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,미세주입된 난자 수,0.120610,0.480217
93,파트너 정자와 혼합된 난자 수_bin,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,파트너 정자와 혼합된 난자 수,0.120610,0.480217
30,난자 출처,알 수 없음,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,NaN,0.120610,0.480217

In [16]:
import pandas as pd
from pathlib import Path

SAVE_DIR = Path("/mnt/c/dev/my_ml_project/analysis/oof_slice")

all_slice_df = pd.read_csv(SAVE_DIR / "all_slice_report.csv")
candidate_slices = pd.read_csv(SAVE_DIR / "candidate_weak_slices.csv")
pair_slice_df = pd.read_csv(SAVE_DIR / "pair_slice_auc_report.csv")

print(all_slice_df.shape)
print(candidate_slices.shape)
print(pair_slice_df.shape)

(146, 12)
(142, 13)
(84, 10)

In [17]:
# 샘플 수 충분 + AUC 낮은 slice
weak_slices = all_slice_df[
    (all_slice_df["count"] >= 3000) &
    (all_slice_df["auc"].notna()) &
    (all_slice_df["auc"] < 0.72)
].copy()

weak_slices = weak_slices.sort_values(
    ["auc", "count"],
    ascending=[True, False]
)

display(weak_slices.head(50))

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std,source_numeric_col,abs_calibration_gap
45,배아 생성 주요 이유,배아 저장용,9192,8,9184,0.000870,0.042063,0.041192,0.448688,0.026437,NaN,0.041192
63,이식된 배아 수_bin,0.0,36544,30,36514,0.000821,0.071417,0.070596,0.550100,0.036001,이식된 배아 수,0.070596
98,배아 이식 경과일_bin,1.0,6053,1132,4921,0.187015,0.370344,0.183330,0.606298,0.119561,배아 이식 경과일,0.183330
117,배아_이식_집중도_bin,"(0.167, 0.667]",57172,24175,32997,0.422847,0.804224,0.381377,0.608740,0.163511,배아_이식_집중도,0.381377
99,배아 이식 경과일_bin,0.0,24904,6252,18652,0.251044,0.453350,0.202306,0.615225,0.143071,배아 이식 경과일,0.202306
100,배아 이식 경과일_bin,5.0,81459,32946,48513,0.404449,0.767590,0.363141,0.619864,0.186849,배아 이식 경과일,0.363141
102,배아 이식 경과일_bin,4.0,4504,1551,2953,0.344361,0.666717,0.322357,0.625448,0.185063,배아 이식 경과일,0.322357
124,배아_이식률_bin,"(0.111, 0.25]",57534,22385,35149,0.389074,0.738783,0.349709,0.627238,0.188458,배아_이식률,0.349709
125,배아_이식률_bin,"(0.25, 0.5]",52879,16277,36602,0.307816,0.587119,0.279303,0.644432,0.210972,배아_이식률,0.279303
51,신선 배아 사용 여부,0.0,39924,9166,30758,0.229586,0.429630,0.200043,0.653818,0.166171,NaN,0.200043
106,배아 해동 경과일_bin,0.0,39801,9141,30660,0.229668,0.429720,0.200052,0.653998,0.166080,배아 해동 경과일,0.200052
54,동결 배아 사용 여부,1.0,40126,9205,30921,0.229402,0.429068,0.199666,0.654270,0.166247,NaN,0.199666
64,이식된 배아 수_bin,2.0,110845,34483,76362,0.311092,0.586404,0.275312,0.655963,0.219070,이식된 배아 수,0.275312
142,배아 해동 경과일_performed_bin,1,40369,9229,31140,0.228616,0.427800,0.199184,0.656018,0.167664,배아 해동 경과일_performed,0.199184
10,특정 시술 유형,Unknown,26939,6390,20549,0.237203,0.444176,0.206973,0.656616,0.172311,NaN,0.206973
103,배아 이식 경과일_bin,3.0,57924,14989,42935,0.258770,0.494740,0.235970,0.656934,0.205637,배아 이식 경과일,0.235970
118,배아_이식_집중도_bin,"(0.667, 1.0]",147652,37163,110489,0.251693,0.477515,0.225822,0.657938,0.198239,배아_이식_집중도,0.225822
65,이식된 배아 수_bin,3.0,8880,1496,7384,0.168468,0.305845,0.137376,0.666380,0.139728,이식된 배아 수,0.137376
34,난자 기증자 나이,만31-35세,6366,1943,4423,0.305215,0.596870,0.291655,0.670852,0.246755,NaN,0.291655
46,배아 생성 주요 이유,"기증용, 현재 시술용",3784,1437,2347,0.379757,0.709398,0.329642,0.671984,0.268099,NaN,0.329642
140,배아 이식 경과일_performed_bin,1,212785,65192,147593,0.306375,0.581246,0.274871,0.675002,0.242982,배아 이식 경과일_performed,0.274871
68,총 생성 배아 수_bin,"(5.0, 9.0]",59403,20149,39254,0.339192,0.654290,0.315098,0.677120,0.262573,총 생성 배아 수,0.315098
35,난자 기증자 나이,만26-30세,4976,1733,3243,0.348272,0.640814,0.292543,0.678621,0.255231,NaN,0.292543
29,난자 출처,기증 제공,15769,4974,10795,0.315429,0.604024,0.288595,0.682562,0.250394,NaN,0.288595
83,혼합된 난자 수_bin,"(9.0, 13.0]",43496,14712,28784,0.338238,0.646546,0.308308,0.683138,0.268419,혼합된 난자 수,0.308308
13,특정 시술 유형,IUI,6100,784,5316,0.128525,0.249689,0.121164,0.684120,0.101224,NaN,0.121164
66,이식된 배아 수_bin,1.0,93791,29408,64383,0.313548,0.600063,0.286515,0.684980,0.261081,이식된 배아 수,0.286515
7,시술 유형,DI,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,NaN,0.120610
30,난자 출처,알 수 없음,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,NaN,0.120610
47,배아 생성 주요 이유,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,NaN,0.120610
52,신선 배아 사용 여부,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,NaN,0.120610
55,동결 배아 사용 여부,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,NaN,0.120610
58,기증 배아 사용 여부,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,NaN,0.120610
61,대리모 여부,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,NaN,0.120610
67,이식된 배아 수_bin,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,이식된 배아 수,0.120610
69,총 생성 배아 수_bin,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,총 생성 배아 수,0.120610
73,저장된 배아 수_bin,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,저장된 배아 수,0.120610
76,해동된 배아 수_bin,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,해동된 배아 수,0.120610
78,수집된 신선 난자 수_bin,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,수집된 신선 난자 수,0.120610
84,혼합된 난자 수_bin,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,혼합된 난자 수,0.120610
89,미세주입된 난자 수_bin,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,미세주입된 난자 수,0.120610
93,파트너 정자와 혼합된 난자 수_bin,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038,파트너 정자와 혼합된 난자 수,0.120610
70,총 생성 배아 수_bin,"(3.0, 5.0]",42022,12227,29795,0.290967,0.561790,0.270824,0.686267,0.252476,총 생성 배아 수,0.270824
94,파트너 정자와 혼합된 난자 수_bin,"(8.0, 12.0]",45248,14788,30460,0.326821,0.629362,0.302541,0.687359,0.267370,파트너 정자와 혼합된 난자 수,0.302541
126,배아_이식률_bin,"(0.5, 3.0]",43235,7879,35356,0.182237,0.348335,0.166098,0.691327,0.170185,배아_이식률,0.166098
104,배아 이식 경과일_bin,2.0,35078,7453,27625,0.212469,0.406952,0.194482,0.691498,0.197500,배아 이식 경과일,0.194482
79,수집된 신선 난자 수_bin,"(10.0, 14.0]",41832,13697,28135,0.327429,0.625866,0.298437,0.691778,0.272430,수집된 신선 난자 수,0.298437
120,배아_생성률_bin,"(0.688, 0.842]",51040,16520,34520,0.323668,0.624259,0.300591,0.697664,0.283898,배아_생성률,0.300591
95,파트너 정자와 혼합된 난자 수_bin,"(5.0, 8.0]",43788,12344,31444,0.281904,0.544642,0.262738,0.701974,0.266400,파트너 정자와 혼합된 난자 수,0.262738
23,시술 당시 나이,만35-37세,57780,16086,41694,0.278401,0.539338,0.260937,0.702349,0.260992,NaN,0.260937

In [18]:
weak_pair_slices = pair_slice_df[
    (pair_slice_df["count"] >= 1000) &
    (pair_slice_df["auc"].notna()) &
    (pair_slice_df["auc"] < 0.72)
].copy()

weak_pair_slices = weak_pair_slices.sort_values(
    ["auc", "count"],
    ascending=[True, False]
)

display(weak_pair_slices.head(50))

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std
69,시술 당시 나이__x__배아 생성 주요 이유,만18-34세__배아 저장용,3169,4,3165,0.001262,0.048917,0.047654,0.100632,0.019672
63,시술 유형__x__배아 생성 주요 이유,IVF__배아 저장용,9192,8,9184,0.000870,0.042063,0.041192,0.448688,0.026437
70,시술 당시 나이__x__배아 생성 주요 이유,만38-39세__배아 저장용,1249,1,1248,0.000801,0.043962,0.043161,0.491186,0.024774
0,시술 당시 나이__x__난자 출처,만38-39세__알 수 없음,1053,108,945,0.102564,0.209079,0.106515,0.540849,0.038561
16,시술 당시 나이__x__시술 유형,만38-39세__DI,1053,108,945,0.102564,0.209079,0.106515,0.540849,0.038561
26,시술 당시 나이__x__특정 시술 유형,만38-39세__IUI,1031,105,926,0.101843,0.209585,0.107742,0.548853,0.038710
27,시술 당시 나이__x__특정 시술 유형,만18-34세__IUI,1976,383,1593,0.193826,0.327971,0.134145,0.587864,0.108959
1,시술 당시 나이__x__난자 출처,만18-34세__알 수 없음,2071,403,1668,0.194592,0.326186,0.131594,0.591422,0.108857
17,시술 당시 나이__x__시술 유형,만18-34세__DI,2071,403,1668,0.194592,0.326186,0.131594,0.591422,0.108857
28,시술 당시 나이__x__특정 시술 유형,만35-37세__IUI,1411,215,1196,0.152374,0.273238,0.120864,0.609835,0.081431
2,시술 당시 나이__x__난자 출처,만35-37세__알 수 없음,1450,219,1231,0.151034,0.272573,0.121538,0.613901,0.081315
18,시술 당시 나이__x__시술 유형,만35-37세__DI,1450,219,1231,0.151034,0.272573,0.121538,0.613901,0.081315
30,시술 당시 나이__x__특정 시술 유형,만40-42세__IUI,1016,72,944,0.070866,0.174654,0.103788,0.624058,0.020882
3,시술 당시 나이__x__난자 출처,만40-42세__알 수 없음,1036,72,964,0.069498,0.174440,0.104942,0.627622,0.020815
19,시술 당시 나이__x__시술 유형,만40-42세__DI,1036,72,964,0.069498,0.174440,0.104942,0.627622,0.020815
32,시술 당시 나이__x__특정 시술 유형,만40-42세__Unknown,4497,898,3599,0.199689,0.366658,0.166969,0.635374,0.135150
33,시술 당시 나이__x__특정 시술 유형,만35-37세__Unknown,6282,1596,4686,0.254059,0.469780,0.215721,0.638181,0.160950
34,시술 당시 나이__x__특정 시술 유형,만38-39세__Unknown,4433,987,3446,0.222648,0.414842,0.192194,0.644650,0.147088
35,시술 당시 나이__x__특정 시술 유형,만18-34세__Unknown,8643,2319,6324,0.268310,0.511741,0.243432,0.649026,0.177650
71,시술 당시 나이__x__배아 생성 주요 이유,"만18-34세__기증용, 현재 시술용",3280,1279,2001,0.389939,0.725741,0.335802,0.660888,0.264857
4,시술 당시 나이__x__난자 출처,만18-34세__기증 제공,2871,880,1991,0.306513,0.617108,0.310594,0.665797,0.238441
5,시술 당시 나이__x__난자 출처,만43-44세__기증 제공,2459,837,1622,0.340382,0.631100,0.290718,0.667978,0.257793
36,시술 당시 나이__x__특정 시술 유형,만45-50세__Unknown,1389,274,1115,0.197264,0.375360,0.178096,0.669494,0.164244
64,시술 유형__x__배아 생성 주요 이유,"IVF__기증용, 현재 시술용",3784,1437,2347,0.379757,0.709398,0.329642,0.671984,0.268099
6,시술 당시 나이__x__난자 출처,만35-37세__기증 제공,1869,594,1275,0.317817,0.603854,0.286037,0.677184,0.250966
58,난자 출처__x__정자 출처,기증 제공__기증 제공,3368,1056,2312,0.313539,0.610159,0.296620,0.677693,0.230604
72,시술 당시 나이__x__배아 생성 주요 이유,만35-37세__현재 시술용,53233,15705,37528,0.295024,0.569439,0.274415,0.679152,0.242461
52,시술 유형__x__난자 출처,IVF__기증 제공,15769,4974,10795,0.315429,0.604024,0.288595,0.682562,0.250394
73,시술 당시 나이__x__배아 생성 주요 이유,만18-34세__현재 시술용,92805,31358,61447,0.337891,0.650697,0.312806,0.682889,0.262984
59,난자 출처__x__정자 출처,기증 제공__배우자 제공,12387,3916,8471,0.316138,0.602491,0.286354,0.683977,0.255492
7,시술 당시 나이__x__난자 출처,만45-50세__기증 제공,3679,1075,2604,0.292199,0.565240,0.273041,0.685464,0.249755
53,시술 유형__x__난자 출처,DI__알 수 없음,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038
55,시술 유형__x__정자 출처,DI__기증 제공,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038
60,난자 출처__x__정자 출처,알 수 없음__기증 제공,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038
65,시술 유형__x__배아 생성 주요 이유,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038
74,시술 당시 나이__x__배아 생성 주요 이유,NaN,6291,811,5480,0.128914,0.249524,0.120610,0.685870,0.101038
37,시술 당시 나이__x__특정 시술 유형,만18-34세__ICSI,52401,17852,34549,0.340681,0.655927,0.315247,0.686389,0.270365
8,시술 당시 나이__x__난자 출처,만38-39세__기증 제공,1619,525,1094,0.324274,0.604799,0.280525,0.686917,0.245488
75,시술 당시 나이__x__배아 생성 주요 이유,만38-39세__현재 시술용,36416,8410,28006,0.230942,0.438658,0.207716,0.689473,0.214859
38,시술 당시 나이__x__특정 시술 유형,만35-37세__ICSI,27185,7861,19324,0.289167,0.561775,0.272608,0.692773,0.256197
9,시술 당시 나이__x__난자 출처,만40-42세__기증 제공,3272,1063,2209,0.324878,0.615519,0.290642,0.699801,0.252916
39,시술 당시 나이__x__특정 시술 유형,만38-39세__ICSI,18080,4033,14047,0.223064,0.420814,0.197750,0.700157,0.224424
40,시술 당시 나이__x__특정 시술 유형,만43-44세__Unknown,1694,316,1378,0.186541,0.343713,0.157172,0.700182,0.173000
20,시술 당시 나이__x__시술 유형,만35-37세__IVF,56330,15867,40463,0.281679,0.546205,0.264526,0.700213,0.260425
10,시술 당시 나이__x__난자 출처,만35-37세__본인 제공,54461,15273,39188,0.280439,0.544227,0.263788,0.700879,0.260519
21,시술 당시 나이__x__시술 유형,만18-34세__IVF,100405,32658,67747,0.325263,0.627744,0.302481,0.702743,0.284783
11,시술 당시 나이__x__난자 출처,만18-34세__본인 제공,97534,31778,65756,0.325815,0.628057,0.302242,0.703639,0.286029
12,시술 당시 나이__x__난자 출처,만38-39세__본인 제공,36575,7889,28686,0.215694,0.412496,0.196802,0.706041,0.220899
22,시술 당시 나이__x__시술 유형,만38-39세__IVF,38194,8414,29780,0.220296,0.420648,0.200351,0.707669,0.225349
41,시술 당시 나이__x__특정 시술 유형,만18-34세__IVF,35273,11640,23633,0.329997,0.639462,0.309464,0.708584,0.296863

In [19]:
gap_slices = all_slice_df.copy()
gap_slices["abs_calibration_gap"] = gap_slices["calibration_gap"].abs()

gap_slices = gap_slices[
    gap_slices["count"] >= 3000
].sort_values(
    "abs_calibration_gap",
    ascending=False
)

display(gap_slices.head(50))

,col,value,count,positive,negative,positive_rate,pred_mean,calibration_gap,auc,pred_std,source_numeric_col,abs_calibration_gap
117,배아_이식_집중도_bin,"(0.167, 0.667]",57172,24175,32997,0.422847,0.804224,0.381377,0.608740,0.163511,배아_이식_집중도,0.381377
100,배아 이식 경과일_bin,5.0,81459,32946,48513,0.404449,0.767590,0.363141,0.619864,0.186849,배아 이식 경과일,0.363141
124,배아_이식률_bin,"(0.111, 0.25]",57534,22385,35149,0.389074,0.738783,0.349709,0.627238,0.188458,배아_이식률,0.349709
46,배아 생성 주요 이유,"기증용, 현재 시술용",3784,1437,2347,0.379757,0.709398,0.329642,0.671984,0.268099,NaN,0.329642
102,배아 이식 경과일_bin,4.0,4504,1551,2953,0.344361,0.666717,0.322357,0.625448,0.185063,배아 이식 경과일,0.322357
71,총 생성 배아 수_bin,"(9.0, 51.0]",39921,13904,26017,0.348288,0.667119,0.318832,0.711014,0.315802,총 생성 배아 수,0.318832
68,총 생성 배아 수_bin,"(5.0, 9.0]",59403,20149,39254,0.339192,0.654290,0.315098,0.677120,0.262573,총 생성 배아 수,0.315098
83,혼합된 난자 수_bin,"(9.0, 13.0]",43496,14712,28784,0.338238,0.646546,0.308308,0.683138,0.268419,혼합된 난자 수,0.308308
91,미세주입된 난자 수_bin,"(9.0, 51.0]",43616,14544,29072,0.333456,0.641121,0.307665,0.706044,0.296019,미세주입된 난자 수,0.307665
96,파트너 정자와 혼합된 난자 수_bin,"(12.0, 51.0]",47556,15679,31877,0.329696,0.635787,0.306091,0.713443,0.307795,파트너 정자와 혼합된 난자 수,0.306091
86,혼합된 난자 수_bin,"(13.0, 51.0]",42671,13876,28795,0.325186,0.629220,0.304034,0.722236,0.317009,혼합된 난자 수,0.304034
94,파트너 정자와 혼합된 난자 수_bin,"(8.0, 12.0]",45248,14788,30460,0.326821,0.629362,0.302541,0.687359,0.267370,파트너 정자와 혼합된 난자 수,0.302541
120,배아_생성률_bin,"(0.688, 0.842]",51040,16520,34520,0.323668,0.624259,0.300591,0.697664,0.283898,배아_생성률,0.300591
24,시술 당시 나이,만18-34세,102476,33061,69415,0.322622,0.621649,0.299027,0.704089,0.285486,NaN,0.299027
79,수집된 신선 난자 수_bin,"(10.0, 14.0]",41832,13697,28135,0.327429,0.625866,0.298437,0.691778,0.272430,수집된 신선 난자 수,0.298437
75,저장된 배아 수_bin,"(2.0, 51.0]",42949,13953,28996,0.324874,0.622863,0.297990,0.769515,0.380499,저장된 배아 수,0.297990
81,수집된 신선 난자 수_bin,"(14.0, 51.0]",48690,15345,33345,0.315157,0.612046,0.296889,0.732422,0.322855,수집된 신선 난자 수,0.296889
35,난자 기증자 나이,만26-30세,4976,1733,3243,0.348272,0.640814,0.292543,0.678621,0.255231,NaN,0.292543
34,난자 기증자 나이,만31-35세,6366,1943,4423,0.305215,0.596870,0.291655,0.670852,0.246755,NaN,0.291655
29,난자 출처,기증 제공,15769,4974,10795,0.315429,0.604024,0.288595,0.682562,0.250394,NaN,0.288595
66,이식된 배아 수_bin,1.0,93791,29408,64383,0.313548,0.600063,0.286515,0.684980,0.261081,이식된 배아 수,0.286515
129,배아_냉동률_bin,"(0.3, 7.0]",51031,15863,35168,0.310850,0.597062,0.286212,0.775822,0.376593,배아_냉동률,0.286212
132,고령여부_bin,0,160585,49147,111438,0.306050,0.590788,0.284739,0.707141,0.280643,고령여부,0.284739
125,배아_이식률_bin,"(0.25, 0.5]",52879,16277,36602,0.307816,0.587119,0.279303,0.644432,0.210972,배아_이식률,0.279303
122,배아_생성률_bin,"(0.842, 1.25]",51027,15412,35615,0.302036,0.579150,0.277114,0.731475,0.303977,배아_생성률,0.277114
64,이식된 배아 수_bin,2.0,110845,34483,76362,0.311092,0.586404,0.275312,0.655963,0.219070,이식된 배아 수,0.275312
140,배아 이식 경과일_performed_bin,1,212785,65192,147593,0.306375,0.581246,0.274871,0.675002,0.242982,배아 이식 경과일_performed,0.274871
121,배아_생성률_bin,"(0.5, 0.688]",45622,13578,32044,0.297620,0.571777,0.274157,0.707010,0.279948,배아_생성률,0.274157
70,총 생성 배아 수_bin,"(3.0, 5.0]",42022,12227,29795,0.290967,0.561790,0.270824,0.686267,0.252476,총 생성 배아 수,0.270824
85,혼합된 난자 수_bin,"(5.0, 9.0]",61680,17858,43822,0.289527,0.560035,0.270509,0.703230,0.269458,혼합된 난자 수,0.270509
90,미세주입된 난자 수_bin,"(4.0, 9.0]",50410,14560,35850,0.288832,0.555211,0.266379,0.703651,0.268974,미세주입된 난자 수,0.266379
95,파트너 정자와 혼합된 난자 수_bin,"(5.0, 8.0]",43788,12344,31444,0.281904,0.544642,0.262738,0.701974,0.266400,파트너 정자와 혼합된 난자 수,0.262738
23,시술 당시 나이,만35-37세,57780,16086,41694,0.278401,0.539338,0.260937,0.702349,0.260992,NaN,0.260937
80,수집된 신선 난자 수_bin,"(6.0, 10.0]",52115,14479,37636,0.277828,0.538442,0.260614,0.712143,0.272574,수집된 신선 난자 수,0.260614
109,난자 혼합 경과일_bin,0.0,201920,55947,145973,0.277075,0.536544,0.259469,0.736036,0.297353,난자 혼합 경과일,0.259469
145,난자 혼합 경과일_performed_bin,1,202616,56073,146543,0.276745,0.535991,0.259246,0.736322,0.297399,난자 혼합 경과일_performed,0.259246
135,고령_난자수_interaction_bin,"(-0.001, 4.0]",207389,56769,150620,0.273732,0.530481,0.256749,0.736518,0.292857,고령_난자수_interaction,0.256749
14,특정 시술 유형,ICSI,122368,33385,88983,0.272825,0.527726,0.254901,0.731333,0.288463,NaN,0.254901
48,배아 생성 주요 이유,현재 시술용,233732,63942,169790,0.273570,0.527529,0.253959,0.719926,0.273973,NaN,0.253959
20,배란 유도 유형,기록되지 않은 시행,194432,52187,142245,0.268407,0.521885,0.253478,0.745400,0.301496,NaN,0.253478
56,동결 배아 사용 여부,0.0,209934,56212,153722,0.267760,0.521066,0.253306,0.748011,0.303546,NaN,0.253306
53,신선 배아 사용 여부,1.0,210136,56251,153885,0.267689,0.520871,0.253182,0.748025,0.303497,NaN,0.253182
22,배란 자극 여부,1,197720,52646,145074,0.266265,0.517370,0.251104,0.746458,0.301275,NaN,0.251104
4,시술 시기 코드,TRYBLT,36713,9879,26834,0.269087,0.519180,0.250093,0.740738,0.294623,NaN,0.250093
107,배아 해동 경과일_bin,NaN,215982,56999,158983,0.263906,0.513497,0.249591,0.750147,0.302943,배아 해동 경과일,0.249591
143,배아 해동 경과일_performed_bin,0,215982,56999,158983,0.263906,0.513497,0.249591,0.750147,0.302943,배아 해동 경과일_performed,0.249591
15,특정 시술 유형,IVF,91755,23990,67765,0.261457,0.510081,0.248624,0.752311,0.302611,NaN,0.248624
1,시술 시기 코드,TRJXFG,36031,9594,26437,0.266271,0.514627,0.248356,0.727333,0.282896,NaN,0.248356
8,시술 유형,IVF,250060,65417,184643,0.261605,0.506303,0.244698,0.738864,0.287975,NaN,0.244698
77,해동된 배아 수_bin,"(-0.001, 32.0]",250060,65417,184643,0.261605,0.506303,0.244698,0.738864,0.287975,해동된 배아 수,0.244698